<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ingresos Mes_panel-tool-collapse panel-to_71da54</name>
   <tag></tag>
   <elementGuidId>12001018-d786-4fb4-9982-306a0734e21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.panel-tool-collapse.panel-tool-expand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divSituacionEconomica']/table[2]/tbody/tr[2]/td/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a144a11a-c89a-4fdf-92fa-4baac8aa8182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-tool-collapse panel-tool-expand</value>
      <webElementGuid>5b79ea28-857a-440a-8efa-29701288238a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>66414066-b94d-4850-b3d3-41a6cb91a08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;panel datagrid&quot;]/div[@class=&quot;panel-header&quot;]/div[@class=&quot;panel-tool&quot;]/a[@class=&quot;panel-tool-collapse panel-tool-expand&quot;]</value>
      <webElementGuid>a01ce286-e15c-4ddb-9475-0926947a52ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d319072-1b1a-4aa6-bcd4-da24e79251c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-tool-collapse panel-tool-expand</value>
      <webElementGuid>1507794b-81e8-4609-92cb-d89b2f2526a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e0b0d9e0-334a-4ce5-954b-60ea0bf5cf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;panel datagrid&quot;]/div[@class=&quot;panel-header&quot;]/div[@class=&quot;panel-tool&quot;]/a[@class=&quot;panel-tool-collapse panel-tool-expand&quot;]</value>
      <webElementGuid>e8cf481f-b4b7-4e05-96b9-38a81961b141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59e98309-e670-450e-a1f6-37a983585453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-tool-collapse panel-tool-expand</value>
      <webElementGuid>7c470156-1d5f-423b-902f-624d3eb18097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b8e84597-11c6-41e5-b352-98adcb821c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;panel datagrid&quot;]/div[@class=&quot;panel-header&quot;]/div[@class=&quot;panel-tool&quot;]/a[@class=&quot;panel-tool-collapse panel-tool-expand&quot;]</value>
      <webElementGuid>667ab13d-7666-4116-90d4-e47326cf4897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35575aaa-f8db-4712-a30d-90f77d0eda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-tool-collapse panel-tool-expand</value>
      <webElementGuid>63d3f775-ae1d-4c3c-b56c-0641b620713d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f75eb32d-447d-4a89-9bed-eb8621ef05a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[2]/tbody[1]/tr[2]/td[1]/div[@class=&quot;panel datagrid&quot;]/div[@class=&quot;panel-header&quot;]/div[@class=&quot;panel-tool&quot;]/a[@class=&quot;panel-tool-collapse panel-tool-expand&quot;]</value>
      <webElementGuid>a0981ba8-5392-4d6f-9f90-940198e91a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divSituacionEconomica']/table[2]/tbody/tr[2]/td/div/div/div[2]/a</value>
      <webElementGuid>cffed9dd-72e7-49c9-9f47-a463b49ef3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[3]</value>
      <webElementGuid>5151be0e-b161-4d34-a91f-6bd0e0a4f7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div[2]/a</value>
      <webElementGuid>0b97c521-a849-43ca-95a7-3ae4d9625645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)']</value>
      <webElementGuid>1537b52c-0d73-4ef2-8f2b-e498cea11d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
