<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b</name>
   <tag></tag>
   <elementGuidId>911182b4-836c-4404-b450-f698cf4bb6cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbTipoDocumento_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>7e23423a-4c23-4f1a-85e9-3a4d134ced9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoDocumento_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>18d6ba9d-e1c1-4942-8e8f-cb7a7c2556c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>630512cb-784a-49d2-a2a4-bfe9bc86e330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoDocumento_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>554ed75b-097e-42f8-8ce3-5fb0c64745b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>3754ed59-5bab-46ea-8908-dfdcd6648fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoDocumento_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>18c5a2cb-032c-401f-bd11-9e823c45c2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>aca2c2bd-5978-444f-b14d-943676f758d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoDocumento_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>d4f8fcf4-4794-48a8-ad90-6e4e6d0b347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6772399a-4ef3-49b2-8575-77239c8f6097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoDocumento_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>4764498b-d448-4475-8a10-692c518ec645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbTipoDocumento_chosen']/a/div/b</value>
      <webElementGuid>f2e6f8b7-2087-4b40-bec9-96ab25d44348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>770cad92-1720-4754-a476-a3d1a789bd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
