<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3</name>
   <tag></tag>
   <elementGuidId>4cc43032-dfc0-4e29-ab58-fa75d3c09345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbGrupoEtnico_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbGrupoEtnico_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>a3885a8c-f609-4883-8800-4cd3bec9a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>4ad846ff-0a8d-4933-a0e6-d02b06bb99f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>fbffbd15-0251-4184-9724-6f174a2439a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>54f2a4b8-fc5f-4c00-bf96-02f0b1079e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>84b22c31-07bf-4ec4-9e96-26bb0a37e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>48ba9e82-9649-4950-8c60-f03e5d61b132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>cbccfdf7-1b3a-4b15-b9db-4edde2cdcc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbNacionalidad2_chosen&quot;)/a[@class=&quot;chosen-single&quot;]/div[1]/b[1]</value>
      <webElementGuid>6ad33645-e223-456b-affb-c1e8977d4a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEtnico_chosen']/a/div/b</value>
      <webElementGuid>b30a42dc-e490-44d1-8a5b-0b14a9b6face</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/div/a/div/b</value>
      <webElementGuid>58d8bd89-9cb7-43d7-b803-0d058b2ccc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbProvinciaReside_chosen']/a/div/b</value>
      <webElementGuid>4a6c28e0-313b-48e0-b28c-73dda65850ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/label/div/a/div/b</value>
      <webElementGuid>17ce666a-5411-4e1e-9e43-c85924699331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbNacionalidad2_chosen']/a/div/b</value>
      <webElementGuid>838c15ac-efaf-41e3-8a5f-dc0870c34cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/a/div/b</value>
      <webElementGuid>fa6acaf3-26ab-44ea-92ef-3e9f3bd7597b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
