<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>fabb756b-cb01-4c7a-9850-717eeff44ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbProvinciaReside_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbProvinciaReside_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>4a45d25b-b881-4134-8f08-c7760e28cc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>72fc33dc-1dcd-4121-a3b0-fdb74a5664d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>64dc28fb-0ddc-4f4f-8c8f-1a2b66bd8944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>2e052b4c-d8fe-4ccf-97e5-f5f9600b0fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>cc51b971-4e0a-48a9-95f9-8b5f22377e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbCantonReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>4ceb026d-ad10-4824-8a9c-7afb76d0f8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>5c54ad7a-d3fe-46b3-ba11-e3a8873da0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>46a38b54-f28a-4a2b-95c1-8d4c040e888a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbProvinciaReside_chosen']/a/div/b</value>
      <webElementGuid>81b1f42e-2ad2-435a-9110-5135e73e74a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/label/div/a/div/b</value>
      <webElementGuid>fbf191a7-855f-4a82-8313-6c600a991895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbCantonReside_chosen']/a/div/b</value>
      <webElementGuid>789acb37-575a-440f-8c51-4be3a8be66ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/a/div/b</value>
      <webElementGuid>b747dd3f-bd35-4a3b-b3ff-4eea17e04ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEtnico_chosen']/a/div/b</value>
      <webElementGuid>0e74303a-d424-47bd-bd0e-acccdbcca578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/div/a/div/b</value>
      <webElementGuid>2744dd18-7285-4d75-986d-d39b03f69312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
