<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>79934469-d41d-4d4d-baf7-0b04a34e4b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbTipoVivienda_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbTipoVivienda_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ea9cd5df-508e-41ce-99c2-45bd44a75c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoVivienda_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>d5a096e8-0a3a-405e-9f29-6b8408c3426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>5636c32b-4c64-4206-8f90-69d5def2b312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbTipoVivienda_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>1d70e7e1-151a-4f57-9c09-5537b32cb5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>e9a75691-fe9e-4486-a257-dac15cdf652b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbEducacion_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>f0d82ce2-f3d7-49f4-8790-a44436e66531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>306ea4fe-e63f-40cd-9c90-eb0abcf06ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbParroquiaReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>1722f6b2-a352-4299-ac15-1699b0de887d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbTipoVivienda_chosen']/a/div/b</value>
      <webElementGuid>80e7b2bf-65bb-46f5-a637-4cfd6828c754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/label/div/a/div/b</value>
      <webElementGuid>d7ab5f28-8d78-4903-8a4b-e6970e97aa33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbEducacion_chosen']/a/div/b</value>
      <webElementGuid>4eee47f5-ecf7-4b55-93b9-0e492698a8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr/td/div/label/div/a/div/b</value>
      <webElementGuid>0d6740df-40eb-4088-b971-db298832dda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbParroquiaReside_chosen']/a/div/b</value>
      <webElementGuid>a128bbea-6d25-40aa-a4b7-a584105be6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/div/a/div/b</value>
      <webElementGuid>8fd2805c-3ae9-4944-8dee-963afcf990d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
