<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Provincia_chosen-search</name>
   <tag></tag>
   <elementGuidId>a2055dc6-de47-4ae1-968a-2f9885a09c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbProvinciaReside_chosen > div.chosen-drop > div.chosen-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbProvinciaReside_chosen']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9390d1cb-3f15-457d-9776-fb23a0371562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>557ab20e-1a73-41c2-9541-8bc4ef274f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>73ffbeb9-2106-4960-81fe-08211b3bf7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1af7855d-15d9-4032-9762-03a758d25612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>0d9db062-89ae-452e-8ced-ec5150f92f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>644eb105-0092-4b50-8143-609ae5df8dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbProvinciaReside_chosen']/div/div</value>
      <webElementGuid>c5f910c0-76ef-46f9-b046-2ef0b9a162c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia...'])[1]/following::div[3]</value>
      <webElementGuid>ed9ff47d-1371-4645-bc4d-9c442af1c573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia reside:'])[1]/following::div[4]</value>
      <webElementGuid>076785d2-fe92-46e4-879f-955e9a41b24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AZUAY'])[2]/preceding::div[1]</value>
      <webElementGuid>26f0414a-f0f2-4e27-94e0-89a301bcd8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOLIVAR'])[2]/preceding::div[1]</value>
      <webElementGuid>ab9a2b4a-7c39-45ff-956e-20e0b0567061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/label/div/div/div</value>
      <webElementGuid>84e4eeeb-ff51-49b2-932f-cb9b91444bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
