<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Grupo_chosen-search</name>
   <tag></tag>
   <elementGuidId>1a71da2e-c625-45c8-9534-68b8fd491f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbGrupoEconomico_chosen > div.chosen-drop > div.chosen-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbGrupoEconomico_chosen']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a21d014c-4dd6-40fd-a226-602d2a699634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>6e72aba3-ddff-44c7-88a1-906dd2457788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEconomico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>bd004d2f-214d-4a68-99db-904c5745987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fab50b7-cbac-440d-a713-61ba770d7b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>b0d0cd79-b721-47cd-9b1e-53d2d831c99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEconomico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>23e9f62c-aae1-4a4f-92b4-f1a0b051381c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEconomico_chosen']/div/div</value>
      <webElementGuid>0eec03e9-3102-4da7-bb5d-7b73c505828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo...'])[1]/following::div[3]</value>
      <webElementGuid>675c9285-eba6-4ebd-b0fe-993d974be745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo económico:'])[1]/following::div[4]</value>
      <webElementGuid>8338dc2e-f162-4231-8f71-5cbcb9be138d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVIDADES ADMINISTRATIVAS Y DE APOYO DE OFICINA Y OTRAS ACTIVIDADES DE APOYO A LAS EMPRESAS.'])[2]/preceding::div[1]</value>
      <webElementGuid>7dd2da1d-5655-4dc8-b9dc-2640db1d7eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS.'])[2]/preceding::div[1]</value>
      <webElementGuid>3924f53f-22d8-4548-b4bb-966c071eaed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[3]/td/div/label/div/div/div</value>
      <webElementGuid>7f17390f-3c4c-4e98-bb22-b2dd87126711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
