<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Actividad_chosen-search</name>
   <tag></tag>
   <elementGuidId>15712bed-d9b9-46db-90cd-c40a8d3e1ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbClasificacionActividad_chosen > div.chosen-drop > div.chosen-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbClasificacionActividad_chosen']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c9720c8-6304-4b67-b24b-988617d03e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>34462e6b-c5e9-441c-add8-8ec46672f9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbClasificacionActividad_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>8a47f712-a6a0-4c2d-a79c-b1e09c134ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b040615-f147-4d72-b5fe-7adbfe159a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-search</value>
      <webElementGuid>1133e964-1b14-4333-85d0-6d5f8199ef7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbClasificacionActividad_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/div[@class=&quot;chosen-search&quot;]</value>
      <webElementGuid>cba1323b-2123-4729-b677-bef5c241b0e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbClasificacionActividad_chosen']/div/div</value>
      <webElementGuid>c4d27649-9063-419a-9e1e-2586214b89a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actividad...'])[1]/following::div[3]</value>
      <webElementGuid>563db48f-c8ed-4081-bdf7-d91913abc682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clasificación actividad:'])[1]/following::div[4]</value>
      <webElementGuid>f86e2a02-8e3d-453d-a7c6-389bf82de3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actividades de fotocopiado y realización de duplicados.'])[2]/preceding::div[1]</value>
      <webElementGuid>fe5b5453-f7bc-4e47-bab9-60deb5b59cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actividades de etiquetado, estampado e impresión.'])[2]/preceding::div[1]</value>
      <webElementGuid>0b01c31d-987b-406d-a0e3-b9c9b192dce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[4]/td/div/label/div/div/div</value>
      <webElementGuid>104dfa1c-79b5-46a1-9b4d-8725b4d1ecab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
