<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_PICHINCHA</name>
   <tag></tag>
   <elementGuidId>218ae163-2196-49ce-bb07-f6670f4da7bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbProvinciaReside_chosen']/div/ul/li/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>31619875-d45a-48a6-b59e-596f8cc2f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PICHINCHA</value>
      <webElementGuid>60ef01bf-7bef-4d30-9e92-e790645acc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProvinciaReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]/em[1]</value>
      <webElementGuid>22cf2fe0-648f-4992-92c8-ef67ae445c74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbProvinciaReside_chosen']/div/ul/li/em</value>
      <webElementGuid>188cefa6-bfbc-4cd3-aff8-6212d4e750b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PICHINCHA'])[2]/following::em[1]</value>
      <webElementGuid>1186717d-e2ca-4a7d-a880-bc9e8b276c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia reside:'])[1]/following::em[1]</value>
      <webElementGuid>313fc379-ac0a-470b-8735-e352986829be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia reside:'])[2]/preceding::em[1]</value>
      <webElementGuid>3e7c7b4c-37bd-49c7-b941-b960dae344d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantón reside:'])[1]/preceding::em[1]</value>
      <webElementGuid>2492f09f-75fe-4e2d-b947-25d16e981856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>fc534cf0-a22c-4f87-8427-c751df73c81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'PICHINCHA' or . = 'PICHINCHA')]</value>
      <webElementGuid>b23dc1e7-788d-42b7-9d65-43133f26316a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
