<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_DIRECCIN</name>
   <tag></tag>
   <elementGuidId>d61c0481-4656-4da0-ba6d-f54dc796d9c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Direccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Direccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6be3b043-1a12-46df-b86f-b8c0e473c507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>bd24171e-a4c6-4fab-acec-f05ce86deeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>c462bc2c-645e-47a5-818b-9bb0e3f7377f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>3c080655-7cf7-40ef-89b6-2c85dcb02311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b0f2bee4-a318-4f58-899e-5412f4e1d8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>ff241336-8da3-4197-b013-3f7688620872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>d0ff5c34-11e1-44d7-8cde-ab3db52d63bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>dbad709f-32b7-4e74-a9ff-6ab6dba7876a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0ff5a22d-c1f0-4ecc-b19f-cc865efaa33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>1799caa5-0f75-42a6-9752-d6d6ce84c58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>8a967052-c061-4d1c-a12c-a2f84888c475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>74374b34-54f2-4370-9ac6-3345ae35ded9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>54a88e93-adec-4c53-b40c-b42da069de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>f12379b9-24a4-42a7-9f50-fd13d6453b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>1cd0606f-aceb-4cfb-9fcd-bb4681ea80a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>255f1f00-98c0-442f-a87c-99d71f449a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>58e82f81-f94f-426d-8e5f-d764ab53a14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>5e922ff5-ddce-4a01-863e-83f491181e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>a81570b2-69ab-456f-876a-bd36933a1629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>2ef7859f-11f8-44bf-8d7b-9d330eb3c712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Direccion']</value>
      <webElementGuid>6f2a7bc2-d2de-483e-bbf4-5a76082f40ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblDireccion']/h1</value>
      <webElementGuid>e0d774ab-9c3c-4272-865a-faff5e62128a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remesas Enviadas'])[1]/following::h1[1]</value>
      <webElementGuid>ab96f9d3-81af-4617-8f71-42550be150a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remesas Recibidas'])[1]/following::h1[1]</value>
      <webElementGuid>6fe4ccec-a7b8-4246-bedb-f9ebab04582e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País de Residencia:'])[1]/preceding::h1[1]</value>
      <webElementGuid>56cf4816-bfb9-45b9-a5ea-4b29bc048095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECUADOR'])[5]/preceding::h1[1]</value>
      <webElementGuid>5b530e13-982c-4922-9c46-8abc28151554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIRECCIÓN']/parent::*</value>
      <webElementGuid>17254bec-a2a1-4682-acde-6cedb74ccd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h1</value>
      <webElementGuid>de2fc1cd-c9d7-4241-800e-ad3a75dd5c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Direccion' and (text() = '
                        DIRECCIÓN
                    ' or . = '
                        DIRECCIÓN
                    ')]</value>
      <webElementGuid>5fe3a26d-6ee6-4b86-8aed-d68d94010da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
