<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_OCUPACIN</name>
   <tag></tag>
   <elementGuidId>826c9f83-cd7d-4fca-897f-d7c40e15867e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Ocupacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Ocupacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>eaf81b51-6cc4-4b2a-852c-19de2b6e6707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Ocupacion</value>
      <webElementGuid>b1695efe-df84-4d87-afca-c1c2ca745bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OCUPACIÓN
                    </value>
      <webElementGuid>3e45746f-1b29-415c-af9a-da3f3e57f5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Ocupacion&quot;)</value>
      <webElementGuid>9f1b4934-86c0-47b9-bd4f-0822a2dcdc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>49887a23-3343-41a6-a2ce-aef670d9bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Ocupacion</value>
      <webElementGuid>ec8b61f5-ac6c-46db-bd79-d7771e5ef058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OCUPACIÓN
                    </value>
      <webElementGuid>f0fb5b2d-9a1b-455d-a131-26085efcbb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Ocupacion&quot;)</value>
      <webElementGuid>1a076a3a-f7ab-4307-a1bc-85e6eb0bce6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7d4630b6-8dc0-464a-9758-7940b75282cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Ocupacion</value>
      <webElementGuid>4fa3cd3c-65f4-44e8-ac7e-7b809b74ebf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OCUPACIÓN
                    </value>
      <webElementGuid>62fed99d-1374-4c29-a32a-e4865678deae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Ocupacion&quot;)</value>
      <webElementGuid>e86fa87b-c783-46d1-91f1-c0dab6467b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>af125f79-12f9-4c9d-b849-cae940e2f0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Ocupacion</value>
      <webElementGuid>9604cda9-425e-4e8b-8690-b6237f66246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OCUPACIÓN
                    </value>
      <webElementGuid>54faae51-2e57-45a4-9d37-3ca366bb690a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Ocupacion&quot;)</value>
      <webElementGuid>c25d11e7-575d-49fc-84fb-f6882f23af1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Ocupacion']</value>
      <webElementGuid>c0f32b49-7069-48e9-90fb-561d18df6499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblOcupacion']/h1</value>
      <webElementGuid>273b5b05-a559-4c54-92e3-d5c395463bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GEOREFERENCIACION DOMICILIO'])[1]/following::h1[1]</value>
      <webElementGuid>34a65dd1-4b30-4c7f-9ccf-f810f6ff835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Obligacion Tributaria 2...'])[1]/following::h1[2]</value>
      <webElementGuid>9152ee1e-ca7f-4543-8aca-5df8d1a48742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educación:'])[1]/preceding::h1[1]</value>
      <webElementGuid>92e43d5f-11f5-406b-b34f-3c904dd379fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educación...'])[1]/preceding::h1[1]</value>
      <webElementGuid>3da51482-c823-4e05-a723-746f07462e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OCUPACIÓN']/parent::*</value>
      <webElementGuid>8e16e93d-82a1-4c0f-81aa-9dc1fab57b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/h1</value>
      <webElementGuid>cf57da16-e5ca-4909-8cc7-0aa3f9765dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Ocupacion' and (text() = '
                        OCUPACIÓN
                    ' or . = '
                        OCUPACIÓN
                    ')]</value>
      <webElementGuid>4494fe97-ad00-4d30-a36b-a060c408d27f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
