<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_OTROS</name>
   <tag></tag>
   <elementGuidId>d736fc2b-a870-4e9c-8299-20046e0f1aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Otros</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Otros']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9a7366df-63a8-4d5f-b863-313429c9587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Otros</value>
      <webElementGuid>240b57c7-b4a5-4a23-8915-6067b01c8728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OTROS
                    </value>
      <webElementGuid>8bd6bd65-1f10-438e-a4ed-bdb81320d76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Otros&quot;)</value>
      <webElementGuid>7ce6cf61-7419-460b-9d89-26dc176e2c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d71d5323-2b62-4f5b-ab21-41a4f8ca82bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Otros</value>
      <webElementGuid>23c5aedb-c730-467e-b250-96a64d54d506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OTROS
                    </value>
      <webElementGuid>0c6f9937-fa07-4a47-b690-2e3aaaa441b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Otros&quot;)</value>
      <webElementGuid>bd00ecb4-eff1-4514-ada9-ae3fdbadbf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1f58baf4-ad0d-4ae2-b0fc-aa3732d86487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Otros</value>
      <webElementGuid>01a959c1-1127-49e3-8a10-cfeef7172c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OTROS
                    </value>
      <webElementGuid>f90e4aea-e0cd-40bd-82b7-fe4c007bb8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Otros&quot;)</value>
      <webElementGuid>c221fa25-3a83-4620-b4ec-d9e0bb874630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>78c27dc7-41ab-46fe-b203-d00454a4d189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Otros</value>
      <webElementGuid>b62b99fd-a1f2-45db-887e-d3cc0f3c7369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OTROS
                    </value>
      <webElementGuid>6b065cd8-f1af-45bd-aebd-6cb3c4fc437a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Otros&quot;)</value>
      <webElementGuid>80abef56-2981-4471-a5c2-0b6b2488ef7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Otros']</value>
      <webElementGuid>8e71c22e-39e9-4e71-a985-6c04047f1dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblOtros']/h1</value>
      <webElementGuid>afc3821f-6807-4909-aeb3-67cf28cb01f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS COMERCIALES'])[1]/following::h1[1]</value>
      <webElementGuid>ecfb930f-7b46-446d-93e3-aa6c1d9ba21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS PERSONALES'])[1]/following::h1[1]</value>
      <webElementGuid>52555c55-6bed-4d70-bb1d-cecb485dc7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propósito relación:'])[1]/preceding::h1[1]</value>
      <webElementGuid>23dd214f-3802-4517-83ad-df1b97f931dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propósito relación...'])[1]/preceding::h1[1]</value>
      <webElementGuid>c9a6b352-1f95-49d8-b51a-290bf8c4a7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OTROS']/parent::*</value>
      <webElementGuid>733517d9-982b-4638-a220-5099597eaae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/h1</value>
      <webElementGuid>2b1d8e5b-53bc-47fe-a415-e3b023c87376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Otros' and (text() = '
                        OTROS
                    ' or . = '
                        OTROS
                    ')]</value>
      <webElementGuid>136b5acc-ee1f-4b1d-ab4e-15bb13955f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
