<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_REFERENCIAS</name>
   <tag></tag>
   <elementGuidId>71be9ffb-a363-4bc5-9e78-614bddc647df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Referencias']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#h1Referencias</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7ee173e7-540b-427d-83f7-a3d33118b0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Referencias</value>
      <webElementGuid>b06a9cc2-85aa-4e0d-8771-113537a4d591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        REFERENCIAS
                    </value>
      <webElementGuid>03c92c88-c4ef-4a34-bd9b-3325d272c293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Referencias&quot;)</value>
      <webElementGuid>ac100380-a1a6-441d-846d-d4847f2accc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a6970a2f-1245-4cd0-a5d4-f7f8e82b062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Referencias</value>
      <webElementGuid>de76c13c-b68e-4cea-9fe3-c2d00b182cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        REFERENCIAS
                    </value>
      <webElementGuid>669002dd-e369-4538-a6b5-df34b96c3964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Referencias&quot;)</value>
      <webElementGuid>de6d3471-cf91-4d96-a581-315379dee1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>06d41249-5d4c-4ea7-afca-c332330749a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Referencias</value>
      <webElementGuid>16d516d9-da74-46f7-a2fd-284f57b57cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        REFERENCIAS
                    </value>
      <webElementGuid>1f267b12-33f3-4ef6-82a6-69f8f53392b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Referencias&quot;)</value>
      <webElementGuid>9c63d9c1-7a76-42bb-9c8f-8ad595071345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Referencias']</value>
      <webElementGuid>fca0817c-8419-4ee0-8065-82addb241f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblReferencias']/h1</value>
      <webElementGuid>1a49a77b-e1e9-4aff-a026-4102007ce767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL:'])[4]/following::h1[1]</value>
      <webElementGuid>8aba7a59-12e7-421d-9d63-c3b7eef0bea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[12]/following::h1[1]</value>
      <webElementGuid>87578203-db64-44b8-a06b-0ea4d448fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS BANCARIAS'])[1]/preceding::h1[1]</value>
      <webElementGuid>8a3accd6-288d-4cd3-961d-35527798e6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Cuenta...'])[1]/preceding::h1[1]</value>
      <webElementGuid>38410884-7cfc-4b72-919f-6d5a1c097c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REFERENCIAS']/parent::*</value>
      <webElementGuid>afdbddae-c4f0-4659-aecb-081a1d00d91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/h1</value>
      <webElementGuid>9016bfe1-e289-4e4a-8eca-2be07f09f8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Referencias' and (text() = '
                        REFERENCIAS
                    ' or . = '
                        REFERENCIAS
                    ')]</value>
      <webElementGuid>ab42a13d-410c-46fe-8399-b073301d6b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
