<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_SITUACIN ECONMICA</name>
   <tag></tag>
   <elementGuidId>8aab6122-d38c-4415-aa79-a39867ffac0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1SituacionEconomica</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1SituacionEconomica']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>de162cea-401d-4eff-a6ff-7ec8a7334821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1SituacionEconomica</value>
      <webElementGuid>05440c5e-deaa-43a0-a40d-622cf0cb986e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        SITUACIÓN ECONÓMICA
                    </value>
      <webElementGuid>e1de8edc-a6e1-420d-9728-b27824dae8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1SituacionEconomica&quot;)</value>
      <webElementGuid>e9c45bc0-fcd5-41f8-b214-d7f1227c321f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>d3d79b5c-e015-44b4-a813-620532514b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1SituacionEconomica</value>
      <webElementGuid>195c68c2-771c-454b-8fc4-dd1de57a5d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        SITUACIÓN ECONÓMICA
                    </value>
      <webElementGuid>f2b5018c-4b56-49ae-b5ff-78979a3c8be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1SituacionEconomica&quot;)</value>
      <webElementGuid>aa5b5756-cb76-432c-9cc2-9f8017f03eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>24043979-6f15-411d-a019-afd15c27ab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1SituacionEconomica</value>
      <webElementGuid>fa7c77d7-c5cf-4d58-aaf4-dd91c4918ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        SITUACIÓN ECONÓMICA
                    </value>
      <webElementGuid>c34e68c1-c056-4b46-b4a7-3d83035e94d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1SituacionEconomica&quot;)</value>
      <webElementGuid>414496ce-be35-4ab0-849a-6950cac40868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b64e753b-6df8-4bcc-afbb-df41486bcab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1SituacionEconomica</value>
      <webElementGuid>4ababba2-4911-45e3-b557-c6d1190d5a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        SITUACIÓN ECONÓMICA
                    </value>
      <webElementGuid>789a448e-5910-4054-bc44-8551f05fe197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1SituacionEconomica&quot;)</value>
      <webElementGuid>2bb332f3-26a5-4fe0-80e0-61505c27321c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1SituacionEconomica']</value>
      <webElementGuid>edd9cdba-80dc-4448-b2e3-2bc5651e4583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomica']/h1</value>
      <webElementGuid>f2424534-3e74-41ac-894d-2e810f17da4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor'])[2]/following::h1[1]</value>
      <webElementGuid>ad2d7f72-401e-4ee5-a7b2-66b3ac220b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre'])[2]/following::h1[1]</value>
      <webElementGuid>b40a7ac9-0f02-4852-95c1-db8f0beb00c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Es Primer trabajo:'])[1]/preceding::h1[1]</value>
      <webElementGuid>9d23616e-ac91-4c58-ba4a-498b9b727ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Origen Ingresos:'])[1]/preceding::h1[1]</value>
      <webElementGuid>aaed6486-25be-4c28-9691-76d774b2b7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SITUACIÓN ECONÓMICA']/parent::*</value>
      <webElementGuid>6bc0b4cc-950a-479a-8a36-3977a7607442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/h1</value>
      <webElementGuid>de6f4414-a014-4178-bd59-4e67e82557b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1SituacionEconomica' and (text() = '
                        SITUACIÓN ECONÓMICA
                    ' or . = '
                        SITUACIÓN ECONÓMICA
                    ')]</value>
      <webElementGuid>4389bdc4-e1ef-4aa8-9835-3ef911024a72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
