<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c7b2229c-851d-4a94-92ea-88698ddd4838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='CierraDialogoCRSNatural()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c152b3f5-25c5-4970-9e9b-074c43b42f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Deshacer.png</value>
      <webElementGuid>e2aeed6a-2fb5-40c5-8c4a-ad92384b215d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>957977cc-8339-4bd3-a52e-ef786559276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>08e0d967-3610-4425-a4f6-53d134c6955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8cff0a23-3a4e-4d1a-bc66-d0d3aa8d3235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>dad7b074-06ae-4573-8bc0-a4eb987bf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CierraDialogoCRSNatural()</value>
      <webElementGuid>aed56615-8d08-40bc-9ade-74cd8e75a10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlgMensajeCRSNatural&quot;)/div[2]/img[1]</value>
      <webElementGuid>0cb6f88b-7b22-4b8f-a127-4b3f8674d81d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='CierraDialogoCRSNatural()']</value>
      <webElementGuid>904bcd3a-c347-474c-92ca-03e1831e2e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dlgMensajeCRSNatural']/div[2]/img</value>
      <webElementGuid>189bb947-5f2a-4725-b9ff-7ee140f2593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Cancelar'])[4]</value>
      <webElementGuid>b5976296-560f-4165-b3c0-72d28eb862ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/img</value>
      <webElementGuid>d822e46d-7c1b-49d7-8a21-1b4e24bd575f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/OSCUS.Aplicacion/Images/Deshacer.png' and @alt = 'Cancelar' and @title = 'Cancelar']</value>
      <webElementGuid>ce5ca8c8-8a76-4d6a-bac5-fa27426536d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
