<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Num. Cliente_imgNuevoClienteNatural</name>
   <tag></tag>
   <elementGuidId>289ecdec-c53a-43bc-8ecd-7fadcc275df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgNuevoClienteNatural</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgNuevoClienteNatural']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d47353ec-6a0a-409d-a5a6-61478d6ef8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>f40cd6c1-647b-43f3-ba33-1e3e45ab589a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>3ca905d7-cf81-490b-828c-71555cd85915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>c3a7d5c6-cd4f-4702-a193-8181e06d9dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>9669eff8-8631-414c-a977-e7ea4d61b3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>08bf43fe-39b7-4214-b55e-38b8c5324644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>00af1844-6d9e-41c3-9391-b6078c5151c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34418a74-edd3-4f35-bee8-1fb846a7f932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>77c208b3-844d-406b-ad70-a9b39f62d70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>c28004f3-9c81-44fa-b7e9-d1519bbe920c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>a6e32ed6-ad02-4a72-9330-0706f4a2b8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>1840426b-4baf-4bec-80a0-1d5955c34978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>8b507f02-3b2d-4abe-b789-389e305358d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>c1d481c1-364b-4aff-8ab0-76bc6861c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3eccfc3e-a4e6-446e-a77d-6affbfb8611f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>86975570-7470-4369-b717-761bcbf965e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>e7d12d36-6029-4c41-b7e4-44e79800144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>6bfe1bec-5003-4dac-9d64-8df47fa8e386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>e5c32c6d-29a4-43af-9960-514e7506b90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>31b998bc-efd6-4a9c-ba82-07aab9a2b95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>0452a4f9-9e79-4c17-8d17-49a9d85ba647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b6528b83-1cad-4ad1-8515-6a0592ab1dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>2c2455fd-2f25-4a2b-8688-b23ff8121a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>1ff981d7-3e48-45db-a117-a900c287b5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>bf58dfe0-47aa-4e93-b587-2e9f407f71f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>300f7cc2-31d8-4daa-9e3f-95674b72c638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>d472b723-0706-4443-9758-8e7c5f0fb7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>4c392d36-a5a2-4d4b-a201-c33659eecd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d5fb998-5917-4017-86e0-8018470a9157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>ea6d525a-9ced-41db-890b-b2f8d797d1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>a989c605-17f5-4495-bf62-11ffc7076659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>c5f9a3cf-e315-4e5e-9b2e-888c4e110c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>5d160421-a54e-4503-b8db-8453ca970e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>ef085d19-2342-4c89-8c56-c5abec644de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>7aec9af4-8e35-4cbd-aead-f994d43e4371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgNuevoClienteNatural']</value>
      <webElementGuid>73c36a80-a61a-4e84-8dbd-4bd01da24b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMenu']/table/tbody/tr/td/div/img</value>
      <webElementGuid>f30ff883-40d8-45cc-ac6b-69a7d5478c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Nuevo Cliente Natural']</value>
      <webElementGuid>d4677a8a-9ff8-47a5-a482-2b3b37e86c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/img</value>
      <webElementGuid>2b83c859-7a9a-46ca-8ecf-14c7d8e76630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgNuevoClienteNatural' and @src = '/OSCUS.Aplicacion/Images/Add-New.png' and @alt = 'Nuevo Cliente Natural' and @title = 'Nuevo Cliente Natural']</value>
      <webElementGuid>d291fd09-a9c4-49c9-8545-40927f5b3d80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
