<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Unin libre_ui-datepicker-trigger</name>
   <tag></tag>
   <elementGuidId>b98188ff-6af8-420b-8115-083e3ee5db97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>555db91e-2f4a-4568-8ea7-569bfa11ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>fae177a7-d2ef-44f3-b5e7-1c4528d72452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/black-calendar_x16.png</value>
      <webElementGuid>bc855748-a71c-4b77-9542-825effe360df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>533aa505-13af-4d5f-9392-963c9a5cdfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>410ff218-9789-4301-8c4b-6a5950a39058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>e57a949c-b744-4bf3-8d78-a64bc77fd930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>623e878b-af93-46d6-8911-5fdbd8cff08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>0b9abb59-3989-419d-88cb-ef0ef7328448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/black-calendar_x16.png</value>
      <webElementGuid>f244c6fe-a4d9-4d16-a7b5-8ab6a3c7a293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>e2d01dee-c6ff-4344-bffc-2edbdfdab7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>89ad2679-6336-4394-9cf0-5268260a8042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>8925dc59-de40-47da-bfed-74a7c5876917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>667893be-4f64-4120-8a07-7561fbcf0fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>b7a1e83e-66b4-419f-9128-1da02ed67f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/black-calendar_x16.png</value>
      <webElementGuid>23ff7dfb-3f54-4aa6-b9b1-1da4260a9492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>56ec149d-4e5b-47d9-a982-f8e4a1390fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>De click para seleccionar la fecha</value>
      <webElementGuid>30b7b5b0-c9ac-4243-9369-7b5536aa8ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>121f01f5-8448-41df-881d-daeae20a1fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/img</value>
      <webElementGuid>6aa1bd36-febd-4aa7-a81d-b13075488c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='De click para seleccionar la fecha']</value>
      <webElementGuid>0ddeb0a7-9c4b-4768-8e44-5be11d70fe9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/img</value>
      <webElementGuid>a70c22c5-04de-4012-a3c7-4febe7558700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Images/black-calendar_x16.png' and @alt = 'De click para seleccionar la fecha' and @title = 'De click para seleccionar la fecha']</value>
      <webElementGuid>1cb843cf-508f-4c4c-badb-613a7840129f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
