<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PEP_imgGuardarNuevoCliente</name>
   <tag></tag>
   <elementGuidId>90684cac-86e8-4ba2-b5be-ac769238b7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgGuardarNuevoCliente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgGuardarNuevoCliente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12ebc07b-d889-45d6-acc5-979844b78a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarNuevoCliente</value>
      <webElementGuid>e6d33162-92ed-412f-972e-2d444fac4655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Grabar.png</value>
      <webElementGuid>7b5497a3-f925-4fc8-8acd-f5c35afa64bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente</value>
      <webElementGuid>bf409709-5465-447a-8448-9b2b0c6ef815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente </value>
      <webElementGuid>7c6b0a31-d272-4691-b050-9f92cf368d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarDatos(event)</value>
      <webElementGuid>c32d6e1e-95c9-4aa7-be8a-2c35c96293a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarNuevoCliente&quot;)</value>
      <webElementGuid>20be4cbc-e968-416a-98ed-7bf37eb33d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>437d2593-e5ec-4d88-a877-e40ab20c469b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarNuevoCliente</value>
      <webElementGuid>b53a527a-dc0e-4906-89e6-8c3d7a4ac02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Grabar.png</value>
      <webElementGuid>029506b2-5730-40e4-83ca-f2fc53ce8026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente</value>
      <webElementGuid>3c47d542-ec1f-412d-8daf-74afb94d0513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente </value>
      <webElementGuid>a590f579-8997-4dfa-bb04-ff02477a7608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarDatos(event)</value>
      <webElementGuid>c47e0cab-ef81-4d93-8afd-a558ff28f5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarNuevoCliente&quot;)</value>
      <webElementGuid>21644845-91c6-49c1-ade9-2ce55adc4ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>58d35ad3-e927-451e-b640-07da8d1ca860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarNuevoCliente</value>
      <webElementGuid>43614e5d-ce8a-4c52-b181-6e1d11567ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Grabar.png</value>
      <webElementGuid>2c3a5012-005e-468d-abf2-e0014f244cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente</value>
      <webElementGuid>579e7d3f-ad70-42e9-b502-0d351f31f866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente </value>
      <webElementGuid>b94e0dd6-0918-4c30-babb-f50bd04da2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarDatos(event)</value>
      <webElementGuid>082bd053-34a8-4e42-84d3-045246c196a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarNuevoCliente&quot;)</value>
      <webElementGuid>f5a8d0da-a3ae-4368-9559-22784c26da6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41c25512-a13a-4226-a380-2d50a13cb52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarNuevoCliente</value>
      <webElementGuid>2bee3444-9659-4833-b6dc-68f43ec08046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Grabar.png</value>
      <webElementGuid>bf2c7f6b-2348-488a-a189-c8c656b7e94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente</value>
      <webElementGuid>7bfe097f-2c7b-4aac-a3b0-0682cb60643c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente </value>
      <webElementGuid>17ea7444-afd7-4bba-af71-6e54c4c6e146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarDatos(event)</value>
      <webElementGuid>e2e51c63-ad97-488f-9713-4a842de5b0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarNuevoCliente&quot;)</value>
      <webElementGuid>5e88bb18-bca6-48de-b5a4-ba72d1960166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgGuardarNuevoCliente']</value>
      <webElementGuid>9073ffec-af68-47d6-8c8c-2b39451186aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGuardarEnabled']/img</value>
      <webElementGuid>bd4dfb1a-a38a-4b33-be73-edd6f190893b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Guardar Nuevo Cliente'])[2]</value>
      <webElementGuid>c2a6af3f-1241-4ba3-a2b4-414a0024b059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/img</value>
      <webElementGuid>28ce44fe-9dc1-4080-af02-6f2a5b7b8bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgGuardarNuevoCliente' and @src = '/OSCUS.Aplicacion/Images/Grabar.png' and @alt = 'Guardar Nuevo Cliente' and @title = 'Guardar Nuevo Cliente ']</value>
      <webElementGuid>635fc010-c8fd-4f8e-9c1f-d1b7c2771e64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
