<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unin libre_txtFechaNacimientoPasaporte_1</name>
   <tag></tag>
   <elementGuidId>885dba11-908d-4628-935d-8563351b816b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFechaNacimientoPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aadaf63c-83c7-4343-85f7-977ea0f36db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip hasDatepicker</value>
      <webElementGuid>5747dce3-0931-41d9-9ce8-88a2b190d0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>F. Nacimiento</value>
      <webElementGuid>d8ac9e5c-e261-4943-a5a7-c7133a354c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f50592ea-9b76-4f5c-9cd6-8d165badfa65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>79fb83b2-17d5-4aad-9232-818d66f6a79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>d4a37619-79af-4fd2-aeaf-9bc4e52dc550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return controlIngresoFecha(event)</value>
      <webElementGuid>2892af24-0db3-49b3-b0d7-4c69c8e68913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidarFechaNacimiento(this)</value>
      <webElementGuid>fdf51b69-42a5-45b2-ac72-5c85e964abaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccione: Fecha de nacimiento del cliente dando click en el calendario</value>
      <webElementGuid>4e26bb19-ad68-42a0-8329-81d8b0b56f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFechaNacimientoPasaporte&quot;)</value>
      <webElementGuid>69102b29-ce41-4961-8c07-f8cf22c4e771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      <webElementGuid>ecddb1cc-09b9-497f-b013-b82503fec5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>2d507041-1dd6-425e-bdce-a75bde8db143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>2b88422d-fcfe-4645-8a8c-177566a7b886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'F. Nacimiento' and @type = 'text' and @id = 'txtFechaNacimientoPasaporte' and @name = 'txtFechaNacimientoPasaporte' and @title = 'Seleccione: Fecha de nacimiento del cliente dando click en el calendario']</value>
      <webElementGuid>d3a5a8b9-5ec7-47f6-9bb8-71210cb6412b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
