<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unin libre_txtFechaNacimientoPasaporte</name>
   <tag></tag>
   <elementGuidId>7bf5136a-9cca-4192-b374-e3f84d1de3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFechaNacimientoPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec8aac9-1886-4174-a14c-449a19dd5e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip hasDatepicker</value>
      <webElementGuid>4b4d2456-7a06-4676-894a-c944732778cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>F. Nacimiento</value>
      <webElementGuid>ec82d42c-b128-45bc-a6e3-32d52e08e775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44e41dc9-da3e-463e-9730-a790ac387632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>c6e1af12-9cf5-4e36-bfac-c4a6b996f969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>95113327-df26-4c16-88a0-7cbb793445f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return controlIngresoFecha(event)</value>
      <webElementGuid>c77624d8-58d2-4d0c-8fe4-317a6200b830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidarFechaNacimiento(this)</value>
      <webElementGuid>0e0b237c-e98b-4fba-8445-e4c73932f3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFechaNacimientoPasaporte&quot;)</value>
      <webElementGuid>eaf3ce8b-48a8-4bf2-8c99-0c049f780d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      <webElementGuid>478ff879-fca9-40c9-9ba7-05e8ae55067a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>78b92f8a-19b7-4534-8132-06b1511327f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>9a7bf98c-c66b-4fd9-97da-1ead2b787c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'F. Nacimiento' and @type = 'text' and @id = 'txtFechaNacimientoPasaporte' and @name = 'txtFechaNacimientoPasaporte']</value>
      <webElementGuid>8cd00d0a-6113-4b4f-b5aa-3bfbf0d518bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
