<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alimentacin_txtValorGasto0</name>
   <tag></tag>
   <elementGuidId>564ea358-49fb-44c8-abb5-2e84e9f8b577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtValorGasto0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtValorGasto0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>016bf153-c5b4-4096-bfab-18d68349c810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorGasto0</value>
      <webElementGuid>4abefea2-c8d4-4f8a-bb93-186d44cc3f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8b4b35d-672f-451a-87e2-b718d6e5a029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de7b0a39-897a-4999-8083-4c9a9130a423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemGasto(this)</value>
      <webElementGuid>cb146233-274a-493a-9c20-b3f2dd2fe495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>b9985d8c-4c62-4619-a8f7-3137ebb6f8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorGasto0&quot;)</value>
      <webElementGuid>04350a95-a53d-4f46-b669-6b868fe74490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2cbf508-3ec4-4d0c-8201-72180c458d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorGasto0</value>
      <webElementGuid>5c97aaf1-b7e1-4852-8793-d2e59ad7bcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c3d4c7f-6be2-4040-b482-4a95c6143d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43a2e2e7-b930-4662-a20c-320f8689c000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemGasto(this)</value>
      <webElementGuid>0c8e35a3-21d3-4c19-8820-8dbdb3245697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>aba637d3-e365-47ef-9825-f63d2206f49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorGasto0&quot;)</value>
      <webElementGuid>e2c618bf-12a4-4a93-9aa3-f3c3209d2174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a29ee2fd-06af-4687-86c0-7627433f1ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorGasto0</value>
      <webElementGuid>2f7b7b78-6132-4aa3-8ffa-18c492dec169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5eacb7f-99a0-4f35-9dde-a4125e4402b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9518cc6d-2e4e-46e1-8564-e7f130f0b0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemGasto(this)</value>
      <webElementGuid>bc6d2d9b-8199-4728-bfe5-b1fd7a522243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>12712b69-5c03-4edc-a449-82516864b9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorGasto0&quot;)</value>
      <webElementGuid>9d842ca1-c137-4e1c-b519-14eebe0faf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0505adbc-240e-4472-aa41-d6325f375e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorGasto0</value>
      <webElementGuid>81acbf58-b6da-49c0-9a86-d1d930639421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0bd647f4-79e1-4a3d-a928-79df63aa7ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2909fcee-9108-4d9e-b6f5-37e3b7a588f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemGasto(this)</value>
      <webElementGuid>26d910ad-a162-4c42-9a13-34f11e74d1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>e443ada4-39b3-468d-b0c7-e215f91a6f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorGasto0&quot;)</value>
      <webElementGuid>ece38fee-fbaa-4137-8ba0-e86aa0977ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtValorGasto0']</value>
      <webElementGuid>9512965f-a828-43af-abaa-a56d4fb1270e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r4-2-0']/td[2]/div/input</value>
      <webElementGuid>250355be-b492-4c14-aa86-ac40af3a7041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>1957242c-e51f-4065-8e23-3862610eab03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtValorGasto0' and @type = 'text']</value>
      <webElementGuid>66c9f8a2-b42a-4b4a-a68d-1f4bfae448ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
