<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Propios_txtValorIngreso0</name>
   <tag></tag>
   <elementGuidId>b56ba933-965a-4d3c-88dc-523dbc7f63c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtValorIngreso0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtValorIngreso0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9432b5f4-6254-4d27-81d8-425acca8eeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorIngreso0</value>
      <webElementGuid>40e4f984-a449-41ca-9c97-3db55e0778b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff51e1a5-3d39-4023-9f82-df50a48a1819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cde777e2-f4ea-4c18-b947-4be7cb78d379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemIngreso(this)</value>
      <webElementGuid>c588cd05-7fca-48af-9089-43b13d788966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>1fe29240-c099-4a86-94be-57e616dd44dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorIngreso0&quot;)</value>
      <webElementGuid>47ea23d4-6c58-4dca-85f6-922c93ea0d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce8befbf-fd55-46f7-8d6c-f6f568f25f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorIngreso0</value>
      <webElementGuid>1d8c7de3-13bd-431c-bf01-71086534a76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a2f03f0-7b1d-47c5-ab67-38c0a5235fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53413b02-2fe5-4364-9bfd-557ce1a4812e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemIngreso(this)</value>
      <webElementGuid>1ba80a8a-7149-4ad7-99ca-7779742d32b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>5170b5f4-0c36-4609-9edf-c3a430ad0be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorIngreso0&quot;)</value>
      <webElementGuid>c9e16544-fe9f-4429-aebb-d403039b8915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bc2ee43-fbf8-483c-8d1f-01210a250f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorIngreso0</value>
      <webElementGuid>89a1a338-05c0-416e-ac4d-7f39637a0828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc5a5d01-c0d7-4669-afbc-fdbff8e72798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b1c12b4-5392-44a6-809b-125f28f27e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemIngreso(this)</value>
      <webElementGuid>bd78cf1e-56c9-4712-a85d-b05be52aa643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>c295014b-358c-4961-be96-8b4094e355dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorIngreso0&quot;)</value>
      <webElementGuid>806fbfcd-b8eb-4d01-85c7-4ffb5e12bf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1169500-d172-4a3a-a5d9-6b5c2bfbef04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorIngreso0</value>
      <webElementGuid>9f2e6618-05c5-4a35-88b9-591a80a409e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e54e85a-7f6d-4239-ad06-6a8981e17667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b29256a3-2f20-44c9-b9e2-1882075262c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemIngreso(this)</value>
      <webElementGuid>1599b763-531a-4b44-963e-69aff9a570ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>d92b23c0-d2eb-49a7-b908-28b1ea5f021d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorIngreso0&quot;)</value>
      <webElementGuid>fb6a17c6-5835-4e71-a4e8-c6515994c05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtValorIngreso0']</value>
      <webElementGuid>372b92a1-4133-40cb-a75d-97a02fb000ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r2-2-0']/td[2]/div/input</value>
      <webElementGuid>21a7eef0-02fe-49f1-ac20-6419a5b3d799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>b943727b-6d8d-4b6f-8e64-f8c1ff5bc2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtValorIngreso0' and @type = 'text']</value>
      <webElementGuid>a5ecdcb7-a0a5-45cd-a8ca-e6bba792f5b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
