<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Con Disolucin Conyugal_txtApellidosPasaporte_1</name>
   <tag></tag>
   <elementGuidId>a0f5385a-12a9-478c-bd3e-15600a27950f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtApellidosPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtApellidosPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b94e5a8c-0023-4cda-9f94-96239881e4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>47698adb-b645-434c-97f0-f36b34302e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>a1245724-5ead-4e30-8576-ed664b77eb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f033c72-3c24-4cff-bc82-ba1670ef12fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>2169204e-3c9c-43cd-a77f-91b9a484fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>5b7eef45-e843-4617-9dd5-4e3eb40ae940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>d0e35c70-061f-4152-8c36-99c913624e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>3895c042-a741-4977-af7d-edc3440eb449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>51372dfa-f1ae-4790-9319-be358f4673f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Apellidos del cliente</value>
      <webElementGuid>0d295361-95bf-404a-bf3f-101a33ee015d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtApellidosPasaporte&quot;)</value>
      <webElementGuid>622b0f02-72aa-4319-9429-75abbc689d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56bfdfd4-4bbf-42de-a566-99c8f3a146c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>f18c6857-f3ba-4be1-9bd6-aa5780d4d2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>d2d1d300-3a77-4898-b768-99ce545c29b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be5f8ee8-628d-4f5d-b33a-e665b922206f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>6ed52a6a-afb5-4dfd-813e-a21af820f1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>2aa6a23d-2898-4e5f-9219-29e5085f76d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>35e95c1b-aa45-4514-b080-a3d4278a1541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>cac8c718-f462-418a-8749-7ff4cbf221ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e563e31d-cd47-432c-b262-26ab0314779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Apellidos del cliente</value>
      <webElementGuid>67ff5bba-a36a-49fb-a61e-3037f6fcd45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtApellidosPasaporte&quot;)</value>
      <webElementGuid>a911e64e-9cb5-40c5-9aeb-8434efddf87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0f9a58-c18d-49d5-b99e-f32ba94d6c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>8accc163-f1e0-4fe2-bebf-01e1e15cb3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>f493ff36-a82e-412a-b1f4-86472706b98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5fdf24f-e523-4c93-88b1-42110c09f0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>649339a2-b351-4e8f-b875-86de07d6e2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>1eda458c-1d8d-4c49-be23-a7b661a86d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>9709ccf0-7a31-407b-9a75-d8f6fa160112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>53a7d5ba-d762-4d62-a61c-d1fa0bad0507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>59fc93fe-7235-46bb-9c6c-861796ef4b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Apellidos del cliente</value>
      <webElementGuid>7226c1f7-e012-4c06-a7ab-2ab380f7cad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtApellidosPasaporte&quot;)</value>
      <webElementGuid>38e0cce0-06bc-4853-99cf-6dd32d3e4100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed59969f-c66c-483c-95b2-70915255dd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>fe6370f1-b12e-4af0-b7f2-35d0f7eab78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>7bdc3886-f509-43a7-8ae8-eac3e32aa2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66b8c5c0-ee68-4a9f-ae88-e620748329f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>0f32c99d-07aa-439f-b0c4-9fe264665662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>6991dd15-9954-45a8-a16f-b47febb9e44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>d179c1bc-7e86-46f6-80d1-6d343d2fbe84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>c4b398fa-803a-4c2b-aa89-01724860eddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>407783ce-28e6-4de5-a339-cb00f841db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Apellidos del cliente</value>
      <webElementGuid>9fedf25a-6fe4-4bdc-b3bd-8829087c265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtApellidosPasaporte&quot;)</value>
      <webElementGuid>8bcf3f93-eff5-4f05-be93-cdf89ae11b68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtApellidosPasaporte']</value>
      <webElementGuid>5b4b4024-a6ff-4e85-81b0-b341d9fafe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>0a5ab3af-5fec-45bc-a231-03394ae61b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td/input</value>
      <webElementGuid>74fc777a-a8d2-491c-9394-00310a2b9ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Apellidos' and @type = 'text' and @id = 'txtApellidosPasaporte' and @name = 'txtApellidosPasaporte' and @title = 'Ingrese: Apellidos del cliente']</value>
      <webElementGuid>6d571c81-164b-4675-98d4-7af9ef0ef2ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
