<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtReferenciaDireccion_1</name>
   <tag></tag>
   <elementGuidId>6f0a7ead-fe39-4eec-bece-d0cb653dd06c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferenciaDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferenciaDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea310cdf-e786-4435-9ca1-12f903b2ddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>2717932f-2b1f-4472-93a9-8841f51d07b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>43ed9a23-eb1f-4a79-86f7-22c67767034f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93921e7c-77fb-4158-ba35-bfd981264109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>96080215-4ad2-484b-af1b-5e5520777f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>cd0f7951-1be6-4265-bce0-870c3d56604a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>dbee4741-8c90-4331-96e2-b92a48c3a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Referencia de dirección del cliente</value>
      <webElementGuid>2cc45203-f013-46a9-901c-804ca8774024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>ac1975f2-721c-4d67-952c-152e36f166e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29793bd6-791b-4fd4-b0bd-c4cbc1f12f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>b99960f3-21d5-4f66-b2b8-2b5fd85f9e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>0ccbbaf3-7bcf-482b-bb29-85ed15b62ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8644a15-7090-4fb9-b6c5-1639dfeffb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>e3c8a138-bf8d-4cfb-b4f6-c59580f30e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>f569429e-2362-437b-b0c4-d4833fb8a821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>42e81b01-f3fb-414b-927d-8995f65cd8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Referencia de dirección del cliente</value>
      <webElementGuid>9e9cffce-1776-4597-8f91-e9cc8613d2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>25437127-a935-4fcb-a91f-910cc2a86bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc20f57b-d4b5-4656-ab12-61ef13285343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>2198a92c-e749-41b7-9364-6bf7f3bc4fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>891bdf52-398f-454a-9acd-e9dc47533cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9295a4c5-cf5a-45d6-b363-0b273a95a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>06c70ad4-32ab-416d-b9ad-3edb21a35a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>7a08abf9-8d87-4cd0-b638-c583f1ff7f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ebd80603-ba5d-41ff-ad90-50a628a5b749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Referencia de dirección del cliente</value>
      <webElementGuid>5039a8da-9f8d-44ee-88b9-322e5710872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>94e5d4e2-2398-4cc3-82e4-3c9c4a669385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f955802-2796-43e2-b388-f03a6803646f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>677572e8-cfe3-4cf6-ade3-65eaac9bfb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>15542d76-5eba-426e-b5f5-58bdfc355236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac186ec8-d7d3-43a9-a5f6-35c710be62ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>12067161-fee2-414c-b6da-7b747ad09bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>77677881-ac23-424c-845d-6bab4f556c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>74cc47f7-7224-4096-bf44-76d1475ae1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Referencia de dirección del cliente</value>
      <webElementGuid>d11467ed-98ee-48ac-ba89-aefc936aa81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>d8538eb1-ddf6-4be7-8ba9-cab161d0edee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferenciaDireccion']</value>
      <webElementGuid>6d95b040-2180-41c7-ab93-ce428aa27b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[6]/td/div/label/input</value>
      <webElementGuid>67f3a8ae-fb88-4814-96bf-02e8875f6ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/label/input</value>
      <webElementGuid>57b9b2e4-320f-4447-a015-1542bffe9f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Referencia' and @type = 'text' and @id = 'txtReferenciaDireccion' and @name = 'txtReferenciaDireccion' and @title = 'Ingrese: Referencia de dirección del cliente']</value>
      <webElementGuid>fd3ecda5-deb3-4659-a048-f8045295a494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
