<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtDireccionPersonal_1</name>
   <tag></tag>
   <elementGuidId>4b81df64-4f58-43cc-913b-0f8fdcb9e861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccionPersonal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtDireccionPersonal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7bd95d6-0a63-4ea9-8196-98edbe8e10a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>cf3842d4-4d00-465b-92c4-39ce8f5b647f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>aa8d6e8c-900a-42b2-955b-7d674b790e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ff843d7-40c3-49ec-911a-c86fb3cd82bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>97dc312b-768c-4711-9524-5cd77b50000f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>6f34b4b8-cfe0-4cef-969d-8e4065f4bcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0d9ec0b2-f606-4c1b-9e7f-2dd512c5aeba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Dirección</value>
      <webElementGuid>f11d18ff-7453-46ad-9070-d83ed6244b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccionPersonal&quot;)</value>
      <webElementGuid>f4dc5134-6208-45b4-a180-09347d255d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70b10caf-d42f-4a3b-8b0e-7a7a7cf0f125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>77c4a66c-07a7-45df-893b-c50940eb3860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>1557262e-b150-4f27-8a92-33337cb2dbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>787b942b-e372-4dc1-b687-63c6dfb6cc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>ab855739-1bc9-4ffa-b159-c0bc91624471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>2c436493-5e3e-40a4-bd62-0362b3c67cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1348f115-05c6-4c14-a28c-ac615e332cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Dirección</value>
      <webElementGuid>43837bf4-961c-4628-bcf8-a1e0c5690db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccionPersonal&quot;)</value>
      <webElementGuid>77a12281-a9ef-4810-831f-607abf435e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b5540d6-01a8-4c83-a618-081f27a4869d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>fbe935b0-b416-4ee7-bbf6-efe1ae3ce4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>3e3660cf-f478-4440-ae6d-d1fa95e8ab54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>286bb835-7ee1-48f9-805d-aa782eeb4345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>65f5f35e-9a7e-43fb-ae7a-d5b5519b2546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>0cea58ea-fc82-42fa-b82b-eb97da1b1cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7760c2c4-f5a9-48d3-8cdd-6e20b3199ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Dirección</value>
      <webElementGuid>e1cc88d1-41f0-406b-9219-c81f49a93603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccionPersonal&quot;)</value>
      <webElementGuid>2180095d-5690-4e0f-bb30-5e92fea3a18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccionPersonal']</value>
      <webElementGuid>09240dde-8a47-4723-9a2b-2943a1ce75ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>f94dfbae-32ce-4cd5-ae3d-97dd2591eed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>4995fe66-f1da-4d33-92b3-73a22e3532f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Direccion' and @type = 'text' and @id = 'txtDireccionPersonal' and @name = 'txtDireccionPersonal' and @title = 'Ingrese: Dirección']</value>
      <webElementGuid>d3a133ec-abf4-49e6-8394-5c32d4e0634f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
