<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtDescripcionActividadEconomicaActual_1</name>
   <tag></tag>
   <elementGuidId>06f634fc-8bd4-441a-ad57-cfde1335a451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDescripcionActividadEconomicaActual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae75352b-9761-4832-9037-b214e6f4d857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>8b0687f8-2e01-466a-ae52-0dd7a4fe22c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>d9270010-6217-4438-bc00-3f0901fba173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1015d79-4931-4e9e-96b4-163a49f4adf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>d235ccb9-031c-4800-a242-246c6f3c0789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>acb4c4e7-5b40-4d41-8e25-3dcef3153981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Descripción Actividad Económica Actual</value>
      <webElementGuid>bbd43f24-7950-4499-a472-2651d5c7d12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>445895cc-dcb4-4fa7-9761-fc650c901636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42332f59-3444-4727-9751-e262a7047ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>fd4de98d-951c-4b16-bc65-b492f051458f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>2131c458-9156-453c-8e3c-1fc0d3ddf116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76b35efd-4b5d-4fee-b083-c1cc0d53e860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>4be0b767-fdb7-4ff0-ac06-d78b7d2e22c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>8731dd34-c912-446d-a86e-a5eb30a4e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Descripción Actividad Económica Actual</value>
      <webElementGuid>67748217-5716-4ff8-8731-b905df9d3d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>1d4c6ac4-97f5-42f9-91a9-04ef86d37418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c211d6c-06ea-41c0-97ea-9f9fd4d23689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>a85e100e-745e-4c81-96c2-d4809ee5e2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>8bcba3ba-c5e7-46f0-b140-a61f11b90a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>078f99a2-50f9-40d6-805e-0b15f40f4e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>3aaf443e-5c92-4374-98f3-8066b2fbe579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>b758a3bb-5447-4c5f-a5f1-f8ffa5b87675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Descripción Actividad Económica Actual</value>
      <webElementGuid>6dbd1d34-d9d0-47cb-af3d-f681c497e8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>fd56805f-e0b1-4430-9701-cae80a323902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>a17b5ea6-e1d7-4393-9f89-604f68182040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td/label/input</value>
      <webElementGuid>4bb922e6-f601-456a-ac4c-329753f22d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td/label/input</value>
      <webElementGuid>ac634aec-a766-4059-9375-e54c293d0ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Descripción Actividad Económica Actual' and @type = 'text' and @id = 'txtDescripcionActividadEconomicaActual' and @name = 'txtDescripcionActividadEconomicaActual' and @title = 'Ingrese: Descripción Actividad Económica Actual']</value>
      <webElementGuid>dfa108e0-8f99-4190-816f-2d08ba14951a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
