<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtDireccion_1</name>
   <tag></tag>
   <elementGuidId>8dc785d5-a20b-40c2-a45e-e222ec831dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73a16ccd-a42d-4ea5-ae86-897cd7d5f533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>a5dde227-150a-4101-bb25-84f07419a615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE PRINCIPAL</value>
      <webElementGuid>fb5cfd5e-f1df-446b-916e-324849afbd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ce0c7d9-316d-4f43-84bd-58c9a25c3b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>a692ab86-9165-4857-a7c9-3dda97caaaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>ca419f42-d451-4e1c-b6e8-40a3426b4f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>2e43059b-40f7-40f8-adbb-585c29eb00fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Calle Principal</value>
      <webElementGuid>73ce8376-71d8-4fc8-a8e7-f6c9df08c06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccion&quot;)</value>
      <webElementGuid>b9c20f4b-686c-46a5-8be8-381bdb480501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecda21b3-ddba-4f71-8236-e173a9e038fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>e4dfb717-1e8f-40ff-94c4-15d9a1b84cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE PRINCIPAL</value>
      <webElementGuid>fd132324-056e-439b-a01a-353f6fed69a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a545c38d-2384-4d97-b187-dbf7fabe9553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>158bf190-46df-4765-b348-b95c6cb2c171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>28d64ef2-d272-4b40-8cd6-bc5659922d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>db3110a7-2748-43b6-a74d-4c4327135120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Calle Principal</value>
      <webElementGuid>7ce0fce3-4a5d-4a9f-9d3e-4b9aaaeb9dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccion&quot;)</value>
      <webElementGuid>6a522c76-e3b0-49c9-a97c-03475120ec04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a192ee0-3a87-4cb6-981d-3e76116a2d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>af1f2d14-401b-4aa6-a606-3e1c45248c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE PRINCIPAL</value>
      <webElementGuid>c4d3a318-d73d-477f-a336-012a59b13c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1317a655-dbca-47f5-9ba4-5e5952cfa389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>d5f39e49-31f2-481d-b1fd-7a496ced1c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>e787e814-4cf2-447c-8103-30d6c3af3ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>618f8cb0-f0c0-4397-81a2-4c697d88c61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Calle Principal</value>
      <webElementGuid>1afff666-aa9a-419d-a88e-744cb5961f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccion&quot;)</value>
      <webElementGuid>661c9e34-cacf-423f-af4d-9e11d4005deb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccion']</value>
      <webElementGuid>5d921f69-3a0c-45b8-9a3b-0d8db6f4d262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>718c2084-652b-4358-9bdf-7efb943fb438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>1779cfc3-4efb-48f9-88ce-38b57f57d65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CALLE PRINCIPAL' and @type = 'text' and @id = 'txtDireccion' and @name = 'txtDireccion' and @title = 'Ingrese: Calle Principal']</value>
      <webElementGuid>f948882b-4c6a-4722-8b58-f00f9f190987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
