<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtDescripcionActividadEconomicaActual</name>
   <tag></tag>
   <elementGuidId>199a8e53-641a-4e21-be26-0c46e9024a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDescripcionActividadEconomicaActual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f38fc3dd-df2e-4090-982c-32b454ac4371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>e1865dde-e971-461a-8e8c-6c4e10f7464d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>bc665423-8d34-438b-852a-3be2bcea31e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f62c88ea-55d8-4c6e-b1be-56f59367062c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>f0b2df4e-70a6-4895-b6d9-b1f20dce9b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>3d115db2-8726-4939-9cca-9e54ec9790b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>eda0b22a-737f-43a8-8ed5-636bfb101e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67f8ca3e-9320-4f3d-b3f7-c8e8cf41aaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>36eaadbc-ae02-4288-8582-98210a43588a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>18323484-21ec-48ad-88f5-605d53ba60c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1ac523a-4356-4ad5-9b6d-88fe9d940d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>1ad29f12-f802-4ddb-9422-54999e9a14bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>faa9e529-cc11-414d-9dd7-cc1f91b4cbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>1f7bb215-bfd0-41c8-9357-240ea6f3cb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>307a1a74-50af-4759-9e70-22e45af8ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>952ec9b3-369c-4222-808d-d4eb74c1d241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>c165899c-52f7-416c-8e55-a2e35f16aaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>549af4c9-bbeb-4a40-a5ec-ec14dcc05953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>2421cb4a-21ee-4cbf-9236-f3638d50b61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>6aa03dc3-f532-473f-83d8-919e2a7f7dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>b421171c-b1ea-4dc9-b8a2-9bb551a8739a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e74051d-12d9-4984-bb04-9b46dd334c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>f4c6874f-1525-4fd5-a049-494546c66230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>96bde6ec-df59-49e0-b83e-c09331fdf15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed00826a-74fa-4132-92c2-9dc216829b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>788ed7ed-8413-40bd-ac77-d5d35cf3c137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>75c23db3-6852-4804-ba63-694c19f3d012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>a67d94d2-931f-4f6a-8af6-bfbccc4ca928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>3c7cb660-a290-409c-bcba-58a534fea3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td/label/input</value>
      <webElementGuid>53dda9ad-04fb-4f2e-af62-3c82a5729b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td/label/input</value>
      <webElementGuid>590ae039-d3d0-44bc-a132-5bf53956a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Descripción Actividad Económica Actual' and @type = 'text' and @id = 'txtDescripcionActividadEconomicaActual' and @name = 'txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>fb09b9a4-0f9a-40fe-aa41-7b07d3325269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
