<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Hombre</name>
   <tag></tag>
   <elementGuidId>cbad9c76-adfc-4480-afba-463ddee891a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > label > label.css-label.cb0.radGroup1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/label/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0e82546f-8177-4412-bbd6-fdc0d36a5d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbSexoHPasaporte</value>
      <webElementGuid>79ed0a2b-e05e-4afc-ac0d-7ba90702fbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>2e7905a2-c4b8-408c-8d08-abace48c1074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hombre</value>
      <webElementGuid>75b48448-0229-4ec2-9c5b-082d933550db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/label[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>fa7839e2-b287-4eb5-badf-bec6fd6f0dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b747caef-4d1d-46e3-98e9-1e3f47bcdc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbSexoHPasaporte</value>
      <webElementGuid>4c76ff74-5aa7-4b04-bdcc-f0144a3fbf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>0f9cf1f3-d984-404d-9725-409254bd3295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hombre</value>
      <webElementGuid>c06fa422-384d-47d1-96c2-08746010b6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/label[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>ae917b62-1519-4d51-9b8e-3c34a6f3db68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d09e4c78-cb2a-4a46-b832-1e0f9c87d25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbSexoHPasaporte</value>
      <webElementGuid>f5a25143-ce58-4abe-958a-e2e34b3de895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>a3cf09b0-ec1f-40a5-83d5-ed7831264a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hombre</value>
      <webElementGuid>1ac53477-26eb-48f5-8b40-48461e9fe7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/label[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>cbcd7b86-d7e5-45d8-91f0-591c921d0cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1c826b05-03a9-4d25-9374-f6747268bfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbSexoHPasaporte</value>
      <webElementGuid>2201eb9f-6c57-4289-8f5a-b45e4a26ebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>c20bf3ed-36a3-4ee7-9cd8-48d272fca6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hombre</value>
      <webElementGuid>3b929196-d172-404a-a1be-af8e32dd29b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trBloquePasaporte&quot;)/td[1]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/label[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>5d5db726-6321-451d-8a7e-0d2d15353e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/label/label[2]</value>
      <webElementGuid>40ebb5c7-f0c6-4b53-8a29-dea3429d7519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sexo:'])[2]/following::label[1]</value>
      <webElementGuid>04073250-1b67-4f61-9a07-fb20717b33e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unión libre'])[3]/following::label[3]</value>
      <webElementGuid>1c56da89-92e2-4a9e-9a4e-20cca8f87527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mujer'])[2]/preceding::label[1]</value>
      <webElementGuid>3a3bac0d-7727-4d6d-b203-1b0c79e4286b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País de Nacimiento:'])[1]/preceding::label[2]</value>
      <webElementGuid>6ae81100-546f-421c-b100-6794de601f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/label/label[2]</value>
      <webElementGuid>671af0f9-d05b-4570-8fc5-7a68ef920aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Hombre' or . = 'Hombre')]</value>
      <webElementGuid>7ce9e5b6-326a-445b-b0df-fb4772659c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
