<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SI</name>
   <tag></tag>
   <elementGuidId>80bc199d-5e4f-4fad-bd98-ccb26a4a1243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > label.css-label.cb0.radGroup1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8aa30ade-e922-4ae8-a862-4afe2c1f2f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideSI</value>
      <webElementGuid>95d61388-d32e-4b92-92a6-1d63286e6802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>3d22fa52-3f83-4727-ab1e-f94d51383c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SI</value>
      <webElementGuid>8ed067db-f260-403f-8c7d-ee95d2fc47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>1ed34935-2f43-4b67-85bd-40e1cc37b941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[2]</value>
      <webElementGuid>84b5d210-9dac-408d-a079-4238e606ff5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Es residente fiscal en Ecuador?:'])[1]/following::label[1]</value>
      <webElementGuid>d912a073-6ffc-4940-8d8f-07ec57a36b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo vivienda:'])[2]/following::label[2]</value>
      <webElementGuid>31b6ceb5-ab16-461f-952f-a46f8dd12a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::label[1]</value>
      <webElementGuid>62b8dad4-cd4a-41d0-9ce7-2cb0255dc2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tributa en el exterior?:'])[1]/preceding::label[2]</value>
      <webElementGuid>134d6795-504b-45d3-9781-15100146fdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SI']/parent::*</value>
      <webElementGuid>0c8b810b-7bf2-4c5a-b44b-2b2fe2452402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/label[2]</value>
      <webElementGuid>d9558224-25e1-4d18-a133-d50492c1b0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'SI' or . = 'SI')]</value>
      <webElementGuid>1223aa93-a7de-4cf0-b0c3-73375d33782a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
