<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>1f4ce366-2d23-4616-9466-6b7d0fac0c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#divSituacionEconomica > table.NoBorders > tbody > tr > td > label > label.squaredFour > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divSituacionEconomica']/table/tbody/tr/td/label/label[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7e484e52-5563-4f1e-b037-21de0a50de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkPrimerTrabajo</value>
      <webElementGuid>321a7df2-b5ae-4bec-aa61-88537b2c2158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[1]/td[1]/label[1]/label[@class=&quot;squaredFour&quot;]/label[1]</value>
      <webElementGuid>db405952-149d-4c8d-89a5-5c74be43e5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8d6090fe-c607-479f-b676-7ea5b7f6d302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkPrimerTrabajo</value>
      <webElementGuid>0d137eb0-851a-4a8e-9fdf-1f82c63c5627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[1]/td[1]/label[1]/label[@class=&quot;squaredFour&quot;]/label[1]</value>
      <webElementGuid>1fb0e92c-1644-48db-9083-718c28fa3346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>561f69fc-7e17-441d-83c1-c7f48aeab0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkPrimerTrabajo</value>
      <webElementGuid>f0a0ff02-b079-461d-93a6-bafe162d226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[1]/td[1]/label[1]/label[@class=&quot;squaredFour&quot;]/label[1]</value>
      <webElementGuid>586d5435-30d2-4c9d-aab8-90b3b626c8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>67a48f6d-6827-4864-9813-de75552a1389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkPrimerTrabajo</value>
      <webElementGuid>a837e1ed-2399-4de9-9e55-0dd6bf812329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[1]/td[1]/label[1]/label[@class=&quot;squaredFour&quot;]/label[1]</value>
      <webElementGuid>82d0d345-2202-4d9f-b7cc-8c0b42937265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divSituacionEconomica']/table/tbody/tr/td/label/label[2]/label</value>
      <webElementGuid>5dbba546-6dc0-4c66-8523-a8a58c6a51cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr/td/label/label[2]/label</value>
      <webElementGuid>3e4a182b-e3a1-4788-b8a8-7f60dbc0b027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
