<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NO</name>
   <tag></tag>
   <elementGuidId>7d916daf-89cd-4089-b2b2-eca058faa929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5d53e708-8e33-4efe-b126-838618bf6f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideNO</value>
      <webElementGuid>f7930963-b4c6-4da4-901a-3a2275c1aaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>7a1c7a44-68fc-4061-83e5-a532dccc9bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>d443f104-7b08-4cdb-9fd9-5317437ffb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>56b51a57-07c2-4859-bc69-972c9fc5b442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b5565046-bb8c-4440-943b-5a231950e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideNO</value>
      <webElementGuid>a5a41270-81fc-4c38-a5d3-51d6a376d3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>3b3d4559-4135-4848-83c6-bc7e981454d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>de804780-6980-4a2c-81d0-cb91c1a0bc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>cbd63492-ea39-4f45-80dc-4866355645eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ce51920a-cf1b-4bfb-bc5e-91292897c8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideNO</value>
      <webElementGuid>439a9ef2-3572-4305-ab5e-0221e5d4b9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>68b8efb9-53b4-4062-8485-c699ee7fd6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>2f39ce91-b161-40d6-9610-8e1b235c3d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>582c2c40-7032-4b9d-bf60-92bd59954d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>858ead17-42c8-4ddb-96a2-944d707c368c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideNO</value>
      <webElementGuid>9e91b726-6392-4f08-8c0e-d6082806d51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>c2a00ead-2af3-4364-b21c-f84cb399629b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>a9019c80-00f3-4bc1-95bb-a63e24c8e76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>cdb64ef8-290e-420f-bd61-ce8ccc9830cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[3]</value>
      <webElementGuid>9299f8c3-f0f4-457f-8de7-fd23ca66d48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[1]/following::label[1]</value>
      <webElementGuid>83a35deb-ed04-402b-9b30-bdaebfce6069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Es residente fiscal en Ecuador?:'])[1]/following::label[2]</value>
      <webElementGuid>5ce317b9-d483-430a-a777-290e20ff2e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tributa en el exterior?:'])[1]/preceding::label[1]</value>
      <webElementGuid>b66771a4-9825-41cc-b9d5-1d2c1efeaa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Obligación Tributaria:'])[1]/preceding::label[5]</value>
      <webElementGuid>4c8ec36f-8e5d-4eb2-804d-5dbff52af331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO']/parent::*</value>
      <webElementGuid>0335799f-3bd3-473c-ae2a-9f3a2f664bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label[3]</value>
      <webElementGuid>e5c095a8-a2e6-4945-bc80-2e1ccc5a8d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'NO' or . = 'NO')]</value>
      <webElementGuid>54e64976-1617-4d1e-a18c-695b513050ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
