<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DISTRITO METROPOLITANO DE QUITO</name>
   <tag></tag>
   <elementGuidId>99aa42a6-e3b1-4b67-ac14-029bbfc3d18a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbCantonReside_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbCantonReside_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a9d090fe-6af0-4656-a02a-41c80458a2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>3b91912e-dddb-4fc4-a989-34f52709f4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ecdd11f4-c836-46e5-b24f-0e3fc0d70afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DISTRITO METROPOLITANO DE QUITO</value>
      <webElementGuid>cfd43c9d-dd32-4ad5-bdec-db3db7c4e354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbCantonReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>e5f21de7-ad88-4252-b358-8d3495d4fa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1fe1e81-00ac-411a-a3b3-5b34a90240f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>c82a5caf-9508-4f27-bcb1-ad117a6fa7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c1da12a9-e42d-4e9f-baa5-f08b4bbcd5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DISTRITO METROPOLITANO DE QUITO</value>
      <webElementGuid>74310e85-1632-4e72-8a6b-581330e84e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbCantonReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>ee24619b-c833-417a-96d6-32cf49c95596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2002d9be-165e-4546-80b5-6f6180ba4913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>a2a978b3-9df9-4856-acf5-7180791ab698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>315e2fc7-52a3-44e0-bf5f-d5d48dfa8ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DISTRITO METROPOLITANO DE QUITO</value>
      <webElementGuid>3658ab30-fca6-4749-858b-3cac0aa7485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbCantonReside_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>dd29e5d4-0e55-4565-a012-a4bce844bb25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbCantonReside_chosen']/div/ul/li</value>
      <webElementGuid>80f2478b-061b-4d6e-8392-847d8c45f972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISTRITO METROPOLITANO DE QUITO'])[2]/following::li[1]</value>
      <webElementGuid>9c765f86-f6a4-47d7-8530-b4a4ea5a1cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantón reside:'])[1]/following::li[1]</value>
      <webElementGuid>5236fe51-ae90-4691-98e7-26464d76ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantón reside:'])[2]/preceding::li[1]</value>
      <webElementGuid>07028365-4aab-42b2-8039-e3038f451587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='METROPOLITANO DE QUITO']/parent::*</value>
      <webElementGuid>37f10984-e023-40bb-8fa8-3b5cd7ca4a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/div/ul/li</value>
      <webElementGuid>bf5adf85-1f30-4220-94a1-2f5707e54db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'DISTRITO METROPOLITANO DE QUITO' or . = 'DISTRITO METROPOLITANO DE QUITO')]</value>
      <webElementGuid>01daef8a-0f5f-470f-b59d-6a8d44138266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
