<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mestizoa</name>
   <tag></tag>
   <elementGuidId>e8abfba6-328d-42a6-a38f-c7af9bcecd3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbGrupoEtnico_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbGrupoEtnico_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>67af6277-1e11-4964-b770-b3fa1c4dd374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>9927ba0b-06b9-41ab-ad6d-d17ee092a214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>275d8c32-4eca-49cd-9905-75dfc8bbe4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mestizo/a</value>
      <webElementGuid>4ee06d4d-ec62-465e-9bfd-8011780b3aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>979be71b-1105-4c45-94d1-279caeed858c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8ba56450-ab70-472f-980d-4a55d467c2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>bdbe8459-cb4d-4c49-ae11-d141ca126a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>75089cad-3ee9-459b-a3dd-2c5c93de4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mestizo/a</value>
      <webElementGuid>66528446-92ff-47a3-bb72-1e5237248dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>e1aa2045-f7c3-4201-92b5-90b6e17d49d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b6e251cd-a1e6-4a4b-8c1b-1a8dabf1cb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>6dbf6d27-6807-42fa-bb9a-aeabf91420c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2dcf9a54-eb03-498a-8b8b-2d4037f1434a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mestizo/a</value>
      <webElementGuid>7aabc8cf-af4d-4204-9797-3f40ab4e60bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>afe32535-bf26-4555-8680-b5149efd52a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEtnico_chosen']/div/ul/li</value>
      <webElementGuid>09db770c-eb84-425f-817a-a1685890d235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mestizo/a'])[2]/following::li[1]</value>
      <webElementGuid>a2fee772-290a-462f-8b61-83f150c5cf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo Étnico:'])[1]/following::li[1]</value>
      <webElementGuid>b54845ae-21a7-4a4b-85f5-cd266275f449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montuvio/a'])[2]/preceding::li[1]</value>
      <webElementGuid>b9f54221-b123-40d5-bde1-8f9620401de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De una nacionalidad o pueblo indígena'])[2]/preceding::li[2]</value>
      <webElementGuid>6fc5b35d-45b9-4a60-9ab4-da190f59555f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/div/div/ul/li</value>
      <webElementGuid>9c04868d-ab42-4906-837d-3467d5780c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Mestizo/a' or . = 'Mestizo/a')]</value>
      <webElementGuid>40d373f2-2cd1-46bf-b65a-adc42058dcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMACIÓN REQUERIDA PARA DEBIDA DILIGENCIA AMPLIADA'])[1]/preceding::li[1]</value>
      <webElementGuid>5982fa74-2584-4da2-bd13-bacadcf64b12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
