<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Arquitectos y afinesCiencias Administrat_e51b77</name>
   <tag></tag>
   <elementGuidId>f2930d2b-ca15-4389-acd9-a875ba1de175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbProfesionSBS_chosen > div.chosen-drop > ul.chosen-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbProfesionSBS_chosen']/div/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>e519186c-2ef0-4277-8924-fd2b6833990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-results</value>
      <webElementGuid>dfa7bb56-dc99-45fc-9fdf-2db45b91814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arquitectos y afinesCiencias Administrativas y EconómicasCiencias de la educaciónCiencias socialesDerechoIngeniería y Ciencias exactasMédicos, Biólogos, Veterinarios y otros profesionales de la saludPeriodistasPolicías, militares (fuerza pública)</value>
      <webElementGuid>7e6ace5a-fb0a-4e3f-9577-7012a78ad030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbProfesionSBS_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]</value>
      <webElementGuid>f036539c-9c3a-4d38-9fbc-91a9f43445e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbProfesionSBS_chosen']/div/ul</value>
      <webElementGuid>004dfcd8-c319-40cb-8965-1a0cff3927ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profesión...'])[1]/following::ul[1]</value>
      <webElementGuid>d6180d3e-88a9-4289-8270-b0b9db456b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profesión SBS:'])[1]/following::ul[1]</value>
      <webElementGuid>79fd075a-3a56-4904-ad34-572ebc97db3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/ul</value>
      <webElementGuid>e4430af8-5f51-49fa-92ff-73f39912ba2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Arquitectos y afinesCiencias Administrativas y EconómicasCiencias de la educaciónCiencias socialesDerechoIngeniería y Ciencias exactasMédicos, Biólogos, Veterinarios y otros profesionales de la saludPeriodistasPolicías, militares (fuerza pública)' or . = 'Arquitectos y afinesCiencias Administrativas y EconómicasCiencias de la educaciónCiencias socialesDerechoIngeniería y Ciencias exactasMédicos, Biólogos, Veterinarios y otros profesionales de la saludPeriodistasPolicías, militares (fuerza pública)')]</value>
      <webElementGuid>068132d4-1ca7-41fd-8f8f-677b62373c91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
