<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parroquia_PuertoQuito</name>
   <tag></tag>
   <elementGuidId>ade8241d-5ffd-4f51-a1b1-c1a23799d7bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[3]/td[1]/div[5]/label[1]/div[1]/div[1]/ul[1]/li[54]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
