<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SE_GastosMes</name>
   <tag></tag>
   <elementGuidId>794c2989-2179-4bb6-a046-ef5e4e851662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;divSituacionEconomica&quot;]/table[2]/tbody/tr[3]/td[1]/div/div[1]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
