<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aceptar</name>
   <tag></tag>
   <elementGuidId>77b3934b-ef91-49eb-860a-da609a532619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.l-btn.l-btn-small.l-btn-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id=''])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b010b6dd-4ff8-4ca6-b802-051c1a78c9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>c8f3109e-155d-4dd9-93f9-6759d40d69a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn l-btn-small l-btn-focus</value>
      <webElementGuid>0a91e831-22e5-4eed-ad53-37324cf16336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>08c5f942-581e-4988-9aa3-87bf83b25200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;panel window messager-window&quot;]/div[@class=&quot;messager-body panel-body panel-body-noborder window-body&quot;]/div[@class=&quot;messager-button&quot;]/a[@class=&quot;l-btn l-btn-small l-btn-focus&quot;]</value>
      <webElementGuid>9d5b1783-03b7-46c2-a995-e9c1dff7680f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[5]</value>
      <webElementGuid>3aa32936-1ae9-4c3d-af78-c3d75138aba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente no agregado'])[1]/following::a[1]</value>
      <webElementGuid>6a0226aa-9bb3-429a-b89e-de0c98a84ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[6]</value>
      <webElementGuid>26016aa8-088d-4491-9b00-496d37d3beb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[15]</value>
      <webElementGuid>cbdf01ec-fa5b-45de-a0da-db4ff3d5ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>801558ec-a67d-43c6-8f85-f28c02681e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>1feeb125-22db-484d-840a-b0a985c2d1a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
