<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1</name>
   <tag></tag>
   <elementGuidId>9551e312-8adb-447a-94a2-835510f52155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbNacionalidad1_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbNacionalidad1_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>499d3b80-53c1-461a-a725-bcd3b974715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbNacionalidad1_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>b43df70a-cdd4-471b-a1c8-54f08e0aacd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbNacionalidad1_chosen']/a/div/b</value>
      <webElementGuid>1db6f98f-0f94-4bc9-aa64-f848798e2eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/label/div/a/div/b</value>
      <webElementGuid>449ddd54-bc3a-4879-924c-8f74b5937bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
