<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>976a8c0a-9278-436a-933b-178146f09f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbGrupoEconomico_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbGrupoEconomico_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6f64d887-dfbf-4a6b-ba6d-58bce09d5486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEconomico_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>18b7cb7b-232e-4b34-b036-7fa553cb2558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEconomico_chosen']/a/div/b</value>
      <webElementGuid>2b0b781d-ff5b-4827-8d74-2886b8308038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[3]/td/div/label/div/a/div/b</value>
      <webElementGuid>72b8aa79-b0c7-47a9-b442-6c2a78921ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
