<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>c43e11fc-79bd-41a3-886f-cbacca6d467f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbClasificacionActividad_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbClasificacionActividad_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>3ea884cb-8471-4dff-a689-aa754822e9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbClasificacionActividad_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>1c821b2f-1c3a-4a59-97f2-4b4cc426ce2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbClasificacionActividad_chosen']/a/div/b</value>
      <webElementGuid>5293320f-20df-49d9-8e79-77034fef85d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[4]/td/div/label/div/a/div/b</value>
      <webElementGuid>9743ffdd-4304-4ceb-99cb-d48b581d5a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
