<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>286e4f5b-10e4-451a-94f8-bdc59a0fffe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbOrigenIngresos_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbOrigenIngresos_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>3b873c7c-7f61-485f-8959-45e9cf9b21c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbOrigenIngresos_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>aa8e62da-b1ba-4ec3-aebc-d92d0321e6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbOrigenIngresos_chosen']/a/div/b</value>
      <webElementGuid>e7f6d3bf-1a1f-432b-82a8-0b7d046c2bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/label/div/a/div/b</value>
      <webElementGuid>da1b327a-ac35-48e9-86b2-ef2fc68a2717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
