<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>1b62f6d8-81b3-4fb6-a46e-673f2e6a4919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbOcupacion_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbOcupacion_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>f3cd7a32-0984-419b-ac74-d5d8a30dfd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbOcupacion_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>111c396e-0a4a-4382-b4a0-0d20848d9235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbOcupacion_chosen']/a/div/b</value>
      <webElementGuid>73fffea7-1c12-4ea0-92ec-ec9e80051efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/label/div/a/div/b</value>
      <webElementGuid>5c2c9175-c65e-4f53-8ce4-4e3dba20af3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
