<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>f1780092-0e8a-40c9-81d9-48bf5e4d2b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbCantonReside_chosen > a.chosen-single.chosen-default > div > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbCantonReside_chosen']/a/div/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>1d746581-7c11-4412-b21b-e72285ba53a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbCantonReside_chosen&quot;)/a[@class=&quot;chosen-single chosen-default&quot;]/div[1]/b[1]</value>
      <webElementGuid>cfc15cb9-2267-4135-a885-f54f13e04a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbCantonReside_chosen']/a/div/b</value>
      <webElementGuid>174e8bab-8579-453c-bf64-9611ed425c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/a/div/b</value>
      <webElementGuid>dd43220e-b144-4560-ab84-e47190be0330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
