<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_DIRECCIN</name>
   <tag></tag>
   <elementGuidId>47368ce8-239e-45b6-ba48-026628cd430b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Direccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Direccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1690e39c-7213-4c05-8cde-a06b317bfd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Direccion</value>
      <webElementGuid>c59a7159-f9f3-4ab7-b38f-e57ea03b8d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DIRECCIÓN
                    </value>
      <webElementGuid>cf357a51-56b3-43ef-94b5-4748807525fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Direccion&quot;)</value>
      <webElementGuid>91e9201a-f023-4483-8d3f-504f0d2e8291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Direccion']</value>
      <webElementGuid>74860f81-f554-4d1d-9a8d-1c6f9c7fd041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblDireccion']/h1</value>
      <webElementGuid>c099c6d7-5f54-4ba8-b32c-ce93de115e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remesas Enviadas'])[1]/following::h1[1]</value>
      <webElementGuid>5b47ed31-b710-4ede-8796-0fa7e99f7eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remesas Recibidas'])[1]/following::h1[1]</value>
      <webElementGuid>237532a1-f416-41b4-babc-3d93a0488829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País de Residencia:'])[1]/preceding::h1[1]</value>
      <webElementGuid>a5dd45b5-883c-45c3-86fc-1c5fe8b0ca15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECUADOR'])[5]/preceding::h1[1]</value>
      <webElementGuid>8d61cdb7-dc34-4bf9-b889-bd383b967534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIRECCIÓN']/parent::*</value>
      <webElementGuid>d37a9a7d-2b05-4114-a4f7-d2a74c7288d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h1</value>
      <webElementGuid>62d3c78f-2f6a-4269-936c-749fad270ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Direccion' and (text() = '
                        DIRECCIÓN
                    ' or . = '
                        DIRECCIÓN
                    ')]</value>
      <webElementGuid>3a134f92-1199-4531-b194-508a569efdf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
