<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_OCUPACIN</name>
   <tag></tag>
   <elementGuidId>8346e374-2503-46eb-be3a-0d87f2995c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Ocupacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Ocupacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>08e3eb00-2cae-408a-8e95-9b7b92316f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Ocupacion</value>
      <webElementGuid>b73ed12d-57b8-47db-9d7b-2c8b01cfc3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OCUPACIÓN
                    </value>
      <webElementGuid>ec8531ee-c4ed-480f-a256-f2136a4da9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Ocupacion&quot;)</value>
      <webElementGuid>3339f4de-827a-46ff-9bd4-5601903e0e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Ocupacion']</value>
      <webElementGuid>6e4aeb58-2d75-46af-81b8-0eae92d08ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblOcupacion']/h1</value>
      <webElementGuid>0b008b91-e616-495f-b48e-3c3322a1b329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GEOREFERENCIACION DOMICILIO'])[1]/following::h1[1]</value>
      <webElementGuid>6f6003ff-43d2-42be-b075-92fe9116e359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Obligacion Tributaria 2...'])[1]/following::h1[2]</value>
      <webElementGuid>a1fd7675-e373-495d-aea3-34a1f3b77bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educación:'])[1]/preceding::h1[1]</value>
      <webElementGuid>7c06b785-2dc5-450a-b2aa-c1258a264e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educación...'])[1]/preceding::h1[1]</value>
      <webElementGuid>a6c8166e-eb57-468d-98ab-98b075a61461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OCUPACIÓN']/parent::*</value>
      <webElementGuid>d91ac606-d092-4c80-a5c9-1de25b4bcf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/h1</value>
      <webElementGuid>7d5cdd8a-71b8-4257-9946-9d643200c75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Ocupacion' and (text() = '
                        OCUPACIÓN
                    ' or . = '
                        OCUPACIÓN
                    ')]</value>
      <webElementGuid>4fe6e480-872d-47fb-9b25-eabc4a3d73b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
