<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_OTROS</name>
   <tag></tag>
   <elementGuidId>9c0ee808-333d-459d-9a44-f1c4e7fa46be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Otros</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Otros']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8755b26d-d44c-414a-866e-625c59777b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Otros</value>
      <webElementGuid>927557e5-8796-4e2c-bd62-92235f8dbf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        OTROS
                    </value>
      <webElementGuid>0f6d9117-853b-47be-9cb4-94995a7fdaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Otros&quot;)</value>
      <webElementGuid>9b37833a-a9b3-41fc-8cc4-afcfa6ba6bcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Otros']</value>
      <webElementGuid>00384d1f-f8e1-4f0f-96a4-8d3389912fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblOtros']/h1</value>
      <webElementGuid>110f652e-e456-4ed2-9d2f-a65560ac557b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS COMERCIALES'])[1]/following::h1[1]</value>
      <webElementGuid>e6c419c2-97c2-4ecb-b301-862f12012717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS PERSONALES'])[1]/following::h1[1]</value>
      <webElementGuid>dfb5b667-55d9-4420-98ab-02dba228ac19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propósito relación:'])[1]/preceding::h1[1]</value>
      <webElementGuid>49fd2aa3-35be-45c7-b8ae-46152b320832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propósito relación...'])[1]/preceding::h1[1]</value>
      <webElementGuid>1203627d-f79c-4db8-8d34-93c261d1e0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OTROS']/parent::*</value>
      <webElementGuid>362e7c85-237a-4f9e-b446-07e47e3793f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/h1</value>
      <webElementGuid>51e8a02f-5a71-4d08-bc05-bc33df0caaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Otros' and (text() = '
                        OTROS
                    ' or . = '
                        OTROS
                    ')]</value>
      <webElementGuid>32b20f3e-4688-438a-8b75-51f89cf0c533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
