<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_REFERENCIAS</name>
   <tag></tag>
   <elementGuidId>878847dc-f401-46b4-ae4f-85ded8af0cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#h1Referencias</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='h1Referencias']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cddcfcdc-0e55-4e10-8913-82797a1aa25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>h1Referencias</value>
      <webElementGuid>8c1f6017-87d4-4e88-b70f-4b65870647a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        REFERENCIAS
                    </value>
      <webElementGuid>e21171f5-96eb-46b3-8053-027bde858c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h1Referencias&quot;)</value>
      <webElementGuid>8002c9fb-7bc3-4c5c-9b14-ff17eabd19b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='h1Referencias']</value>
      <webElementGuid>335f133c-8ede-43f4-8fed-3b2e6b9b4bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblReferencias']/h1</value>
      <webElementGuid>e02aa094-9862-481a-9e2b-ccaf96766303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL:'])[4]/following::h1[1]</value>
      <webElementGuid>c359f791-e2cb-4a16-846c-3b7c7337a15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[12]/following::h1[1]</value>
      <webElementGuid>01abcee2-4e2d-425c-ae0a-03184ac97a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIAS BANCARIAS'])[1]/preceding::h1[1]</value>
      <webElementGuid>7e13ac32-16e5-4354-b490-768c64cd6e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Cuenta...'])[1]/preceding::h1[1]</value>
      <webElementGuid>16b46bf4-9411-4f79-8e22-2c4068b97f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REFERENCIAS']/parent::*</value>
      <webElementGuid>dc8b8630-459d-44d7-997d-4ebccdb40972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/h1</value>
      <webElementGuid>b2ab5994-2eaa-403d-9f21-373b19054cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'h1Referencias' and (text() = '
                        REFERENCIAS
                    ' or . = '
                        REFERENCIAS
                    ')]</value>
      <webElementGuid>0c58dace-bd2d-4963-8605-c3b0c625efc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
