<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Num. Cliente_imgNuevoClienteNatural</name>
   <tag></tag>
   <elementGuidId>8c4c2fb6-4cb8-436a-acb3-aeef1cfc696f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgNuevoClienteNatural</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgNuevoClienteNatural']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>893c1bbd-98d1-4fb5-a5b0-298ea11a2615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgNuevoClienteNatural</value>
      <webElementGuid>ba5b096c-9f04-4dad-9dfa-f91ec7b6441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Add-New.png</value>
      <webElementGuid>0e47d16c-3d10-409a-a416-cb07b4eec55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>48d27b26-1d39-4f4e-bc5e-1df2774b52f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nuevo Cliente Natural</value>
      <webElementGuid>46679716-7137-4b1d-9cef-a9aeb42206a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fnNavegar(1)</value>
      <webElementGuid>ca76060c-821a-4592-9df6-6b30168c14ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgNuevoClienteNatural&quot;)</value>
      <webElementGuid>519b3cc2-8be9-4d7d-96bd-2fcdb8a42cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgNuevoClienteNatural']</value>
      <webElementGuid>2cafa181-f14c-456f-abfd-524faf06c97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMenu']/table/tbody/tr/td/div/img</value>
      <webElementGuid>44166f0c-4d86-44ec-a891-9612d159d2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Nuevo Cliente Natural']</value>
      <webElementGuid>62ac0529-4ae8-4f60-937d-f080a7352515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/img</value>
      <webElementGuid>083aa92e-8de1-4bf8-a373-9a197f0cc268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgNuevoClienteNatural' and @src = '/OSCUS.Aplicacion/Images/Add-New.png' and @alt = 'Nuevo Cliente Natural' and @title = 'Nuevo Cliente Natural']</value>
      <webElementGuid>dbe2f3ea-58c7-475d-843f-b58adc82034d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
