<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PEP_imgGuardarNuevoCliente</name>
   <tag></tag>
   <elementGuidId>bcf536a9-e844-4298-a00a-e66d8971399a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgGuardarNuevoCliente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgGuardarNuevoCliente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2bd81546-9736-436a-b411-20f8b568c51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarNuevoCliente</value>
      <webElementGuid>aa4a49d4-7948-405c-9c4a-1f10b24a7af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/OSCUS.Aplicacion/Images/Grabar.png</value>
      <webElementGuid>5b296146-0f03-499e-adf9-6a8291df43a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente</value>
      <webElementGuid>ea7b7a49-fc24-42bb-b978-21760060ea71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Guardar Nuevo Cliente </value>
      <webElementGuid>6766f6fa-d384-4413-8f77-15b28e1093f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GuardarDatos(event)</value>
      <webElementGuid>3589a1a6-72fc-49af-a23b-4a88a13cb45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarNuevoCliente&quot;)</value>
      <webElementGuid>26860a8d-235e-4436-92e6-e3c434dc9543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgGuardarNuevoCliente']</value>
      <webElementGuid>b79649a8-e65b-4cbc-ad33-5d650ad25d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGuardarEnabled']/img</value>
      <webElementGuid>4e2fbfd7-b702-4150-8cb2-e1042f1a9299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Guardar Nuevo Cliente'])[2]</value>
      <webElementGuid>066904f2-ede4-4e1c-923d-c5ab30dd8608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/img</value>
      <webElementGuid>5c93fed5-1e89-49f5-8386-c78ce3d7761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgGuardarNuevoCliente' and @src = '/OSCUS.Aplicacion/Images/Grabar.png' and @alt = 'Guardar Nuevo Cliente' and @title = 'Guardar Nuevo Cliente ']</value>
      <webElementGuid>726d1783-c772-4829-b5d7-128afd71bad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
