<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtTiempoTrabajo</name>
   <tag></tag>
   <elementGuidId>49e88dbc-337a-4242-89d7-39e8ff31d994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTiempoTrabajo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTiempoTrabajo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d48111b7-0a83-4de9-8216-346e9034ed1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>03e0c6a1-c068-42e5-9b92-b13a0830c69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tiempo en el trabajo</value>
      <webElementGuid>2ae7a5d5-bc3e-4d00-a4cd-0d09dba9a027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d677db6-0f77-4ad4-8680-0e85e67d6e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTiempoTrabajo</value>
      <webElementGuid>2b4d43e8-9626-4085-ae65-01272828bf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTiempoTrabajo</value>
      <webElementGuid>906658b3-4ead-4c61-a882-4e58d87537ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>0dd6b595-bf90-4b09-8890-71f0ec4af899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTiempoTrabajo&quot;)</value>
      <webElementGuid>0e510cd6-39c7-498d-862f-231b9d5ca017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTiempoTrabajo']</value>
      <webElementGuid>3012333f-eb71-4228-9aab-eb7bffa13bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td[2]/label/input</value>
      <webElementGuid>64c774f2-cc6f-4fba-b87c-9254d5d0b8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td[2]/label/input</value>
      <webElementGuid>9ff1f366-41b2-4f69-b2cf-0750d415bba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tiempo en el trabajo' and @type = 'text' and @id = 'txtTiempoTrabajo' and @name = 'txtTiempoTrabajo']</value>
      <webElementGuid>e3d6c5be-cabe-4e71-a42b-ac42bdc92de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
