<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtReferenciaDireccion_1</name>
   <tag></tag>
   <elementGuidId>1c08f3ed-4b50-46e6-b92d-f7df49885950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferenciaDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferenciaDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e99d81a-87e0-4a02-b5f5-eb972a1c933a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>77816288-d28b-4245-9a9d-59861a5951c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>80c226d2-cff3-4771-920b-21e3982830c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c997b4ae-0521-418b-b70c-03eb753deeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>48bee076-09ea-49b9-98aa-b3d8f9edfc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>7526afa7-7f66-4a8c-9e62-5349cc775474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c36620d9-efec-419d-b7ed-07ae57527867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Referencia de dirección del cliente</value>
      <webElementGuid>39290ea5-2bbf-47cd-8497-514ea39087bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>2374214d-3a04-4c4d-8e5f-fb01979774b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferenciaDireccion']</value>
      <webElementGuid>3e3e2e24-b375-4b4f-a1d7-283721d3efd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[6]/td/div/label/input</value>
      <webElementGuid>9d56a8c2-5c74-41a5-88de-9c848798344b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/label/input</value>
      <webElementGuid>7ffa5804-d656-4e9b-be20-13d57161e689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Referencia' and @type = 'text' and @id = 'txtReferenciaDireccion' and @name = 'txtReferenciaDireccion' and @title = 'Ingrese: Referencia de dirección del cliente']</value>
      <webElementGuid>2784f6a1-862d-45e7-89b5-f1bc1e656cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
