<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtTelefonoCelular</name>
   <tag></tag>
   <elementGuidId>1dcd25ea-d273-4f53-acc5-92782f517c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTelefonoCelular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTelefonoCelular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>230ac03e-3670-4fd7-bea5-af376ce91ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>8988ecb3-87f1-48e2-8101-063b1da37fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Celular</value>
      <webElementGuid>f5da0a87-aa16-4fbe-9a9f-2896fd5f90af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea340bff-2406-4a1e-9b53-08e73eef352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTelefonoCelular</value>
      <webElementGuid>b5c947d6-75b9-46ba-af77-c17c792a7b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTelefonoCelular</value>
      <webElementGuid>cf7b85eb-a0ef-48c2-ba8a-b3f590a433b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>44fe72bc-6ec5-413f-baa2-5e87b1f85baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>923b1967-3dd3-4d4b-8947-e5bd68456f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTelefonoCelular&quot;)</value>
      <webElementGuid>d145bf9f-5dac-4dbc-b4fa-fca405964381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTelefonoCelular']</value>
      <webElementGuid>8cf0e7e1-c042-42e9-97e0-d0aa7c325bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[3]</value>
      <webElementGuid>6be8d704-c494-4cbe-8fa4-970748063b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input[3]</value>
      <webElementGuid>7ba92e5f-3e46-4a11-83e0-a218e042611a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Celular' and @type = 'text' and @id = 'txtTelefonoCelular' and @name = 'txtTelefonoCelular']</value>
      <webElementGuid>d2a195e6-ed0a-446f-8a80-c775ece06fca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
