<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtDescripcionActividadEconomicaActual_1</name>
   <tag></tag>
   <elementGuidId>7df6ee6c-8c52-4fae-90d6-2190d0e06aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDescripcionActividadEconomicaActual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2e1061f-a2f5-4c69-985f-be02db084c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>9e3ae691-599a-447f-b1af-1b16ca988184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>07b170b7-75ec-4a37-964c-ae1c6fc92470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed3fcd5d-21df-4bd7-8e2e-1cb027240ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>edbc6678-67c4-453a-81d1-9680812540fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>e1be3bfe-9a40-4960-9177-924834bbf57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Descripción Actividad Económica Actual</value>
      <webElementGuid>4331c652-e723-4887-bb10-39c0c2624cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>812d9b8c-2098-48dd-8bce-edda9f4d3832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>66a99b20-58ae-416f-aeb8-92ed80805ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td/label/input</value>
      <webElementGuid>13d16f46-4f62-4b47-aad4-b75d652bc6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td/label/input</value>
      <webElementGuid>3e432cec-8260-402b-897f-0ed097910791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Descripción Actividad Económica Actual' and @type = 'text' and @id = 'txtDescripcionActividadEconomicaActual' and @name = 'txtDescripcionActividadEconomicaActual' and @title = 'Ingrese: Descripción Actividad Económica Actual']</value>
      <webElementGuid>9f0c947a-1fe0-47d3-8cbf-5a8520584d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
