<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtParentesco_1</name>
   <tag></tag>
   <elementGuidId>4c89ddad-0803-4203-9df3-785bcd0ce02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtParentesco</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtParentesco']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13bd8a83-7a9e-42b0-89f0-e49720955037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>e344cd4d-556d-46d9-a54f-b83a23336ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parentesco</value>
      <webElementGuid>69086ace-641e-49ec-87d6-bc4d1e6322b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb7856f5-178f-4185-8eac-f8c41d900503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtParentesco</value>
      <webElementGuid>46e07758-5198-4aaf-904a-4a55d00141f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtParentesco</value>
      <webElementGuid>e9455a5f-de84-4e4e-a18e-64d46373ed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>00742038-53a7-45cc-9025-afa11fb41a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>0f832710-2b19-4305-9904-865203517f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Parentesco</value>
      <webElementGuid>7db01fe8-f43f-4afa-b57f-eda99dab83df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtParentesco&quot;)</value>
      <webElementGuid>70851af1-d3b1-49d3-b7f0-177b05b81edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtParentesco']</value>
      <webElementGuid>5efbb200-6881-4a09-adac-8c20f842c797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[4]</value>
      <webElementGuid>c316b242-9734-44c7-8f2f-f124c7a4ccb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input[4]</value>
      <webElementGuid>aa1c0993-fbc8-4976-903e-b9abee9f48d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Parentesco' and @type = 'text' and @id = 'txtParentesco' and @name = 'txtParentesco' and @title = 'Ingrese: Parentesco']</value>
      <webElementGuid>58d2d868-ebc9-43ef-beaf-2972f4d18032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
