<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtReferenciaDireccion</name>
   <tag></tag>
   <elementGuidId>2bdc8a41-a602-4a5a-af95-a5743bbe594e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferenciaDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferenciaDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dab72b93-000e-4888-b00e-000860101ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>645e4245-7b6a-47c0-b478-8f34cbca6ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencia</value>
      <webElementGuid>9ef27b0b-3f89-4641-85d3-0cbe74a706cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0aee2cee-a8f9-4dcb-8124-31cddc278d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>d735a5f3-f9d7-4b66-b0fa-cb2994d0dabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReferenciaDireccion</value>
      <webElementGuid>29214a91-ec66-4ad7-a55b-0e79c2ad9587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>08971ad9-f0cb-48bf-b416-42988856f80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferenciaDireccion&quot;)</value>
      <webElementGuid>3dcc7953-2e74-45b5-af15-bcf3de76b912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferenciaDireccion']</value>
      <webElementGuid>7413655c-b8bf-41d2-be0b-1bde727f03a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[6]/td/div/label/input</value>
      <webElementGuid>a1152dcc-a593-4e23-854d-1934d2b40f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/label/input</value>
      <webElementGuid>35a52beb-e186-4cb5-9659-7ec3377ee00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Referencia' and @type = 'text' and @id = 'txtReferenciaDireccion' and @name = 'txtReferenciaDireccion']</value>
      <webElementGuid>38c5e313-a875-4050-965d-9afe900d07a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
