<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtDireccion_1</name>
   <tag></tag>
   <elementGuidId>23917c32-0287-419f-b08c-8736a71ff487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a518ca7f-4809-4eab-aafe-4e8f2a1eba48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>72219624-7816-463f-9a4c-5b5032974929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE PRINCIPAL</value>
      <webElementGuid>1fbfc292-e08f-4a6e-a7a7-fea298ba47ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e046b714-3eb3-427f-b600-0f25e54a577f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>effdd042-a503-4d8d-96ae-f7b728a75fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>fc0616a2-da22-4e92-971a-13ba3a735308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>15d94656-f838-4916-b8a0-5a563e38b8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Calle Principal</value>
      <webElementGuid>13145a59-546f-4910-81cd-fe29dd2146e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccion&quot;)</value>
      <webElementGuid>e20ace4c-06aa-41ba-a22e-594094fa2316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccion']</value>
      <webElementGuid>5e684ab1-7e75-4b08-84e4-906deb1db016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>3fa6f464-ce94-403b-8356-6c75f34d7b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>299658a4-c68e-4edf-9c74-674a22876f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CALLE PRINCIPAL' and @type = 'text' and @id = 'txtDireccion' and @name = 'txtDireccion' and @title = 'Ingrese: Calle Principal']</value>
      <webElementGuid>8f41347e-a8c1-44d0-b070-99ff9444a385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
