<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtDireccionPersonal</name>
   <tag></tag>
   <elementGuidId>44835c2a-d4ae-4a83-b429-357aa2bff2b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDireccionPersonal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccionPersonal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0ff597c-6c26-4198-be9d-321f037ec93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>806dee67-59bc-4c5d-8498-3c0e998e43a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>70e95453-04af-4fbb-84e4-d3a3c1350487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>280feba6-234c-4e12-8a0a-dc8c0aef88a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>3348257c-d915-4130-aa2a-55e9e4a4bb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>29e271c1-d1f7-4bc6-82cd-685949d92a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1410db7f-a365-4d11-ba17-a0b53cc7320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccionPersonal&quot;)</value>
      <webElementGuid>1671e66c-b432-4950-a7fa-9c72067eefc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccionPersonal']</value>
      <webElementGuid>239fb352-1642-4e42-b54b-041ff33cc4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>cc347284-e991-4338-aaf0-c8c214276791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>5d1ed6dc-d117-4bc6-8a8d-970a89f236f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Direccion' and @type = 'text' and @id = 'txtDireccionPersonal' and @name = 'txtDireccionPersonal']</value>
      <webElementGuid>601451d8-58a4-4368-8f68-ceb3313ce760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
