<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alimentacin_txtValorGasto0</name>
   <tag></tag>
   <elementGuidId>70605020-660a-436a-a639-d940dd301da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtValorGasto0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtValorGasto0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fd5c448-233b-4d42-b091-31072b8352bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorGasto0</value>
      <webElementGuid>b4a232c5-b80b-44dd-8e65-4f12e5d0e0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5191c5f-a6f3-4b00-bede-08961d9bed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f26ed0fb-d357-41fa-806e-b1dc62b2e201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemGasto(this)</value>
      <webElementGuid>8d8f05be-7110-4896-b5e6-9ebbf4b382a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>b659cb4d-bc8c-40eb-b152-7b6aea02f4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorGasto0&quot;)</value>
      <webElementGuid>222321d2-bfaf-416b-8d4c-af67f4f8ead6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtValorGasto0']</value>
      <webElementGuid>320e3264-ca6a-41b1-b8c7-837f2d38b059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r4-2-0']/td[2]/div/input</value>
      <webElementGuid>bc508b9b-7306-4be3-9ecc-eb3815de2be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>4a4d0a14-13c8-4964-b008-668c5b8855e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtValorGasto0' and @type = 'text']</value>
      <webElementGuid>d6efeae7-332a-4076-bf4e-b3ccd139b1b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
