<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtCelular1</name>
   <tag></tag>
   <elementGuidId>05e1c2c3-593c-45da-8194-29796e636791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCelular1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCelular1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96d329e3-5eeb-43b9-9115-0a59efd97e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>e7cabe2a-c40b-4742-b5cd-29ddea0430d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Celular 1</value>
      <webElementGuid>d7a9ea15-7e14-4ff3-b966-738058246f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef1cb3c3-f2c7-443b-bae8-b61e971abfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCelular1</value>
      <webElementGuid>04cc4bc9-14c9-42e9-90b9-c5609d670550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCelular1</value>
      <webElementGuid>4a075ed5-01cc-420e-b81e-548ed486dbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>VerificaCelular1(this.value)</value>
      <webElementGuid>186ebd18-fba3-4a20-aa50-a18a7c37f6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>41afa380-13ad-44a8-a1dc-2ab87f8b155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fda6a6f8-5726-420c-a6b0-12bf586cff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCelular1&quot;)</value>
      <webElementGuid>1ce41c27-8146-4a80-9349-3f57e4f6e2b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCelular1']</value>
      <webElementGuid>63be6a88-a5f2-4007-83e5-4f38d33776c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[7]/td/div/label/input</value>
      <webElementGuid>dca3e385-e7c0-4c72-a112-e027f63ff022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div/label/input</value>
      <webElementGuid>63887b91-83ef-46e2-b1d5-fb437471298b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Celular 1' and @type = 'text' and @id = 'txtCelular1' and @name = 'txtCelular1']</value>
      <webElementGuid>ccb07206-93ce-48b8-9e16-61002223cd4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
