<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtTelefonoCelular_1</name>
   <tag></tag>
   <elementGuidId>ed0e172d-e91f-477e-ae20-03d7ddfce2c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTelefonoCelular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTelefonoCelular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36d9ee2d-7c3e-44bf-b97b-73433569e3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>ae06ac40-9253-4780-b683-8f61b49670f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Celular</value>
      <webElementGuid>a63ee537-7704-41d3-9318-197d39b659b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8f6734f-c23d-4f4e-bd75-d6bb08d10e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTelefonoCelular</value>
      <webElementGuid>20372ace-7262-4224-99c8-155ee9a71797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTelefonoCelular</value>
      <webElementGuid>b612c0d4-20d3-4d9d-896b-b03260f5a527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>fe2902d3-145a-4a54-95b0-9ff2ad34497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6b43cbf0-be50-4673-9263-fb6aa7efbe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Celular</value>
      <webElementGuid>48899ced-1cfb-4b5c-90c8-219d2e80a654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTelefonoCelular&quot;)</value>
      <webElementGuid>beb0bad2-a010-4767-a0c2-8d95765807cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTelefonoCelular']</value>
      <webElementGuid>0b6f94ee-e6c5-4bc4-ac44-117bd7f8baff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[3]</value>
      <webElementGuid>55fad5fc-0266-466d-8427-ca4b779a5b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input[3]</value>
      <webElementGuid>9a9a6ac2-4bcc-4ea3-a2c5-d4217c4d484a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Celular' and @type = 'text' and @id = 'txtTelefonoCelular' and @name = 'txtTelefonoCelular' and @title = 'Ingrese: Celular']</value>
      <webElementGuid>67a0962f-1083-4089-8fc8-736a32b58216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
