<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Con Disolucin Conyugal_txtApellidosPasaporte_1</name>
   <tag></tag>
   <elementGuidId>10ead798-9beb-4a7b-851b-455251ad6e59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtApellidosPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtApellidosPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7d852a0-6b53-4d0b-95b4-aed839fd5c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>2d3bad51-04bc-485d-a670-c18ca3bbaefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>197d3c6b-b6f5-476c-ac18-bad42b6f69d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef898bc8-e350-4391-b918-dfbd40b79baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>2137a803-ecf0-4554-aee0-6b4a90a9d170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtApellidosPasaporte</value>
      <webElementGuid>85b9d93c-e6ba-4880-813d-c934e7c55454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>d1849a82-e84f-4b85-bcb4-938a8ad0875b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>2b25d9cb-410d-4a66-ad37-a574cc8f28fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9274e33d-7344-4e49-80b9-d7057026cbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Apellidos del cliente</value>
      <webElementGuid>92bf41f1-b604-4230-8938-3ce4f07399ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtApellidosPasaporte&quot;)</value>
      <webElementGuid>1ea94b54-9fdd-4625-90f7-f32ce7ec3ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtApellidosPasaporte']</value>
      <webElementGuid>3c2623de-1050-4a10-b028-dce8156a2de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>8d70c773-c9a1-4125-8859-5d200a486bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td/input</value>
      <webElementGuid>8a607483-39b3-4ad3-8711-5449e736db37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Apellidos' and @type = 'text' and @id = 'txtApellidosPasaporte' and @name = 'txtApellidosPasaporte' and @title = 'Ingrese: Apellidos del cliente']</value>
      <webElementGuid>f87a4f0a-4bfa-40c7-a1a0-0449fac2806c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
