<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtDireccion</name>
   <tag></tag>
   <elementGuidId>2986db9b-d4f7-4c9d-bdd9-4eab4579b9ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDireccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aca487fe-61f3-4b32-a20c-f233dc018154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>1ac9602b-edac-4fb4-9b8c-af0895299fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE PRINCIPAL</value>
      <webElementGuid>661fdc8b-cb4f-4e51-9303-1ed07191bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b3fd0bc-8ad5-494c-b552-8026e76c3bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>14623b3e-072b-4090-823a-4e96a86b32d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccion</value>
      <webElementGuid>94f70d74-3945-44c8-8c25-db9dcb3d7b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>81b579d6-2b31-4e2d-91d1-4d54f971dc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccion&quot;)</value>
      <webElementGuid>c9180095-ef40-41b9-974a-fc8915e1496c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccion']</value>
      <webElementGuid>c2409913-1a17-4656-9457-41bf42181fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>21dbd0df-9c28-45fa-afe7-d7b02483779d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr[4]/td/label/input</value>
      <webElementGuid>7f01e991-5a7e-4d5b-974f-029d46e80077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CALLE PRINCIPAL' and @type = 'text' and @id = 'txtDireccion' and @name = 'txtDireccion']</value>
      <webElementGuid>0a459b44-9438-4997-a72d-d5d31c871401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
