<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Propios_txtValorIngreso0</name>
   <tag></tag>
   <elementGuidId>4e0d513d-6dfb-4e31-a57e-0fc0501e6805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtValorIngreso0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtValorIngreso0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87c3a212-d11c-4a00-91e8-a26a8a90e85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtValorIngreso0</value>
      <webElementGuid>c0ae3aa6-4d22-4541-8b66-b5824b6338c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49bd2205-0161-4d96-9992-c009c7bacd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7238c5e-5204-47d8-ba2d-e84a81c503f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CambiarValorItemIngreso(this)</value>
      <webElementGuid>9f7822ad-cbdf-4bcf-9b08-b70156e047c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateDecimalNumbers(event, this)</value>
      <webElementGuid>19c4bc8d-86d9-4cce-a0c8-fa8a1f472e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtValorIngreso0&quot;)</value>
      <webElementGuid>b1dedd71-a4e6-4b99-906e-97be70a1985a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtValorIngreso0']</value>
      <webElementGuid>d3c47747-2f24-4681-8ea8-74ef700ea51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r2-2-0']/td[2]/div/input</value>
      <webElementGuid>1b6802b0-cdbe-4e8b-ac86-d323c58a3df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>33a91d21-6cbc-40f9-97ab-107f1d37166a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtValorIngreso0' and @type = 'text']</value>
      <webElementGuid>44be6e47-ac6f-4d00-b79a-e98e8b18db73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
