<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtCalleSecundaria</name>
   <tag></tag>
   <elementGuidId>8d2810c7-9e18-4b3e-b7b8-b342fc729e42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCalleSecundaria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCalleSecundaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7774fa2d-c556-4534-9cfd-34c71c6bbd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>3b92647e-86dd-4316-b362-b00add0402b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE SECUNDARIA</value>
      <webElementGuid>81233a15-7428-45bd-b3ca-2de93219b6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f8b33f3-9587-46be-b7d4-51578b49f452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCalleSecundaria</value>
      <webElementGuid>b997a9d5-961f-40fc-aa74-410d06f28966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCalleSecundaria</value>
      <webElementGuid>1d31a07a-1af4-424e-bc45-bf6be8c1cf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>f929e3f4-4c15-49de-8f41-f5bb0cf6cf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>948b0b52-dfa6-4b11-b250-f5e4f9a499a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCalleSecundaria&quot;)</value>
      <webElementGuid>d0f62db8-e323-4397-bd35-bf106a07cec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCalleSecundaria']</value>
      <webElementGuid>04fcdce0-f0bd-4f32-807e-34a35c0c5e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[5]/td/label/input</value>
      <webElementGuid>d9a6cc9a-d252-482e-baba-00e9ce5e71a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input</value>
      <webElementGuid>cd92ec8e-bb3b-4051-a4ea-da7a6535ba94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CALLE SECUNDARIA' and @type = 'text' and @id = 'txtCalleSecundaria' and @name = 'txtCalleSecundaria']</value>
      <webElementGuid>8e9342ab-2bdd-45c5-980e-331515c3e6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
