<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtCalleSecundaria_1</name>
   <tag></tag>
   <elementGuidId>46dabc1e-525d-40bd-bec0-e9eeb0bd874c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCalleSecundaria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCalleSecundaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e44b26d-eacb-428c-9d59-544378ebc38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>4dcdd16e-b826-41c4-947e-728410965cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CALLE SECUNDARIA</value>
      <webElementGuid>16738636-3a56-4123-bcae-e13b4149ad74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b1bad2b-abde-4887-b662-aebd479bd00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCalleSecundaria</value>
      <webElementGuid>325c2c0b-be51-4fcc-a187-4713de7a9e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCalleSecundaria</value>
      <webElementGuid>63eff666-8b9c-4389-8b77-da50b9192823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3fbfcb49-d1c6-41e5-9c02-ca57d480752d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ExcluyeComillasSimplesAndDobles(event)</value>
      <webElementGuid>30c9e349-936e-4643-a76a-7a2cfb99a5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Calle Secundaria</value>
      <webElementGuid>368691f8-be7b-4336-9498-b0b34ba4b9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCalleSecundaria&quot;)</value>
      <webElementGuid>a59937da-3cfe-4880-b21e-11fa1facf6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCalleSecundaria']</value>
      <webElementGuid>b87ae4c8-56bb-41d5-83c3-32a797fad669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[5]/td/label/input</value>
      <webElementGuid>205f5128-2eaa-48b5-af80-73ac9a0004dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input</value>
      <webElementGuid>c78a4bf0-70d7-43bf-bc92-2120f016ed7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CALLE SECUNDARIA' and @type = 'text' and @id = 'txtCalleSecundaria' and @name = 'txtCalleSecundaria' and @title = 'Ingrese: Calle Secundaria']</value>
      <webElementGuid>4ca58fe8-7b62-4e27-ae3c-7c7277311e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
