<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtDescripcionActividadEconomicaActual</name>
   <tag></tag>
   <elementGuidId>e8d1a48f-4526-4a94-8021-cb9f6a7e40d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDescripcionActividadEconomicaActual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>672b97f2-4be4-43a9-9ddd-7abde9b0a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>8fca87ee-5ee4-42b1-8713-4114fe17c35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Descripción Actividad Económica Actual</value>
      <webElementGuid>c53f9d3a-77d2-41fe-83e2-9bec4fd2b2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8db1c42c-1be1-42b2-9b74-68b52d54ae7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>66d34dfc-d4ff-407e-8b52-1584eccfc303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDescripcionActividadEconomicaActual</value>
      <webElementGuid>55c287df-3bde-44ef-8c59-495e1a4644fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDescripcionActividadEconomicaActual&quot;)</value>
      <webElementGuid>0330cd8c-2d73-4e10-acb4-b205ddeaaf3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>48a959ad-4a0d-498c-ad32-e218638434c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td/label/input</value>
      <webElementGuid>21b952b4-4ef4-457a-8230-1d0a5d5d4983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td/label/input</value>
      <webElementGuid>c55346e6-bdeb-4f11-86c7-13364bb3b4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Descripción Actividad Económica Actual' and @type = 'text' and @id = 'txtDescripcionActividadEconomicaActual' and @name = 'txtDescripcionActividadEconomicaActual']</value>
      <webElementGuid>8d65e456-a771-4aa3-9928-720070c4e364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
