<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtNombrePersonal_1</name>
   <tag></tag>
   <elementGuidId>3cb32b03-eea0-4084-9ce5-76532065db39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNombrePersonal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNombrePersonal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff2228b3-6a55-4a33-8250-b90f49a277ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>21b3972b-4dd0-45a7-ab7b-373dcbdac03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre</value>
      <webElementGuid>0809c12c-3dc5-40e0-a127-871d84809f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b6eecd2-d5d0-4d35-93e3-b837b9da73c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNombrePersonal</value>
      <webElementGuid>830166da-32de-4917-8c09-926ee4916bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNombrePersonal</value>
      <webElementGuid>ea9875b8-1520-4e13-950c-a2f7c6876ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>934afee7-3e4f-4289-9ee2-451fdda4c5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>eed07671-1b00-4938-8247-9394c9b21653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Nombre</value>
      <webElementGuid>f1824a57-ece0-4dd0-a01e-7912f6844dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNombrePersonal&quot;)</value>
      <webElementGuid>de7bcb1d-3f5a-4b72-97c4-ca4c2a9ca3f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNombrePersonal']</value>
      <webElementGuid>27e2da6b-09d4-4d35-9e5c-4df0fabeaffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input</value>
      <webElementGuid>36bb4888-04ba-48c7-95a6-6025694ba8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[5]/td/label/input</value>
      <webElementGuid>6bdd6136-01d5-4d75-b84d-ad7318b469b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nombre' and @type = 'text' and @id = 'txtNombrePersonal' and @name = 'txtNombrePersonal' and @title = 'Ingrese: Nombre']</value>
      <webElementGuid>253aa430-c1ec-4f46-a89b-ac34e0a932d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
