<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cantn_txtTiempoTrabajo_1</name>
   <tag></tag>
   <elementGuidId>5a01dec6-752b-4395-baf8-6040c86c060f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTiempoTrabajo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTiempoTrabajo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0aa7089-7763-45d8-a1a3-fa5af67fd0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>a04c654c-eb73-44d4-89e5-cc08d9cbc75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tiempo en el trabajo</value>
      <webElementGuid>1fe25a40-aae5-4381-aa6f-b1bdcb1a0c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>264f2f63-e373-4759-9d7b-52e1f9cfccb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTiempoTrabajo</value>
      <webElementGuid>296f20a9-fc64-494a-82cb-5adfcfbfd958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTiempoTrabajo</value>
      <webElementGuid>52fbed1c-b004-4781-9d4f-03af357a73c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>2f5b88ff-6750-4d20-9cbb-b1c0ae4284b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Tiempo en el trabajo/Actividad Actual (AÑOS)</value>
      <webElementGuid>2bb9cdb8-96f5-4dc2-9ec4-d3471c669f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTiempoTrabajo&quot;)</value>
      <webElementGuid>9bd8a88c-7c92-4d63-94ed-cf3862fbf918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTiempoTrabajo']</value>
      <webElementGuid>b45906ea-f864-47d5-884d-36f2075820bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lblSituacionEconomicaActividad']/table/tbody/tr/td[2]/label/input</value>
      <webElementGuid>0388487c-5b1d-4e12-ba07-703cd0badb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/table/tbody/tr/td[2]/label/input</value>
      <webElementGuid>9a913e03-4876-4336-b2bb-e8bf6147599e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tiempo en el trabajo' and @type = 'text' and @id = 'txtTiempoTrabajo' and @name = 'txtTiempoTrabajo' and @title = 'Ingrese: Tiempo en el trabajo/Actividad Actual (AÑOS)']</value>
      <webElementGuid>e0315c71-55e2-43b2-bc89-58caa6e1fe90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
