<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Con Disolucin Conyugal_txtNombresPasaporte_1</name>
   <tag></tag>
   <elementGuidId>5078ad41-e714-4d02-bab4-e72226191ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNombresPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNombresPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b6c6c9-a146-4cd9-a148-07ca5af8c0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>cc43293d-80f4-4760-82ea-44a6f5e48ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombres</value>
      <webElementGuid>63e5de3b-0991-4244-8b65-0cac5a5fd281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4693d792-95ae-46da-a862-c5571be8031c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNombresPasaporte</value>
      <webElementGuid>a7c1e5ec-7130-4e98-b9f9-ae9270c50993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNombresPasaporte</value>
      <webElementGuid>5c2b26b6-733d-416d-8c36-01037d68c3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>663717a2-1fed-42b2-b0b4-707cb70b7831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>ListaControl()</value>
      <webElementGuid>88cb5450-074b-465b-8820-5373f075bb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>daf787c3-a340-4073-af1a-3a3934763ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Nombres del cliente</value>
      <webElementGuid>53d163b5-17bd-43f4-b34f-1abd4806d1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNombresPasaporte&quot;)</value>
      <webElementGuid>baeacdb2-1683-48be-b27e-7d186a9a91d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNombresPasaporte']</value>
      <webElementGuid>9d300425-a883-42c6-9c03-c71e29092f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr/td/input[2]</value>
      <webElementGuid>383bbae3-176b-4174-894c-c0b016beccb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td/input[2]</value>
      <webElementGuid>b3268666-b4b1-45dc-a6a7-625f5d7153cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nombres' and @type = 'text' and @id = 'txtNombresPasaporte' and @name = 'txtNombresPasaporte' and @title = 'Ingrese: Nombres del cliente']</value>
      <webElementGuid>4f1a64d3-31f8-4b44-863b-a0aaf08738c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
