<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parroquia reside_txtCelular1_1</name>
   <tag></tag>
   <elementGuidId>4196c591-cb87-4552-94de-5c74568d99ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCelular1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCelular1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9d7ced6-20b2-4f9e-bc2c-004c26da33f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>54d696e6-1359-46e3-9fbf-5676d2e07294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Celular 1</value>
      <webElementGuid>7b91bc04-fb67-4d2b-8345-73ab6b0a5635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9c69075-9381-426d-b20f-538b72772447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCelular1</value>
      <webElementGuid>789f3aae-cbc1-466f-905e-e4718e426b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCelular1</value>
      <webElementGuid>e57907e5-ed10-48ea-8e95-1bd48a451e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>VerificaCelular1(this.value)</value>
      <webElementGuid>f2da7774-66c2-4fdd-912d-39510f705b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>bc1cab8e-8d51-448b-8f66-7192df377204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>41b68d2f-3167-48a9-97b3-67c4e23ade5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Celular 1 del cliente</value>
      <webElementGuid>68bacf62-b6c7-4f8d-bf5d-804fc2784b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCelular1&quot;)</value>
      <webElementGuid>130d18c8-6ce9-4d2f-998b-301187643c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCelular1']</value>
      <webElementGuid>4b594616-57fd-4346-b767-5bc4cc347136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[7]/td/div/label/input</value>
      <webElementGuid>5c9240c7-ec4b-4300-8f6c-12e9668c61be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div/label/input</value>
      <webElementGuid>add1f6e4-703d-4943-9ffe-3a27f40e0d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Celular 1' and @type = 'text' and @id = 'txtCelular1' and @name = 'txtCelular1' and @title = 'Ingrese: Celular 1 del cliente']</value>
      <webElementGuid>0c1f5d5e-51f4-4690-aa7d-9627a53730ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
