<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unin libre_txtFechaNacimientoPasaporte_1</name>
   <tag></tag>
   <elementGuidId>09615a20-6d50-46a2-9389-b79693d1b6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFechaNacimientoPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8668b950-a0db-4e97-a14e-fac844c9c62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip hasDatepicker</value>
      <webElementGuid>654b0398-2229-4d17-b033-c87a9b46ca3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>F. Nacimiento</value>
      <webElementGuid>525a740b-e641-4c78-a00f-091a513743f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6b9bde2-e709-455b-9058-35fb09997328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>ed00baa1-f845-4781-90b0-19663185f6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>243072b4-d40e-4fae-8e23-8af5e2bf0956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return controlIngresoFecha(event)</value>
      <webElementGuid>67293cd7-9ce7-488d-91c8-f7439f7375c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidarFechaNacimiento(this)</value>
      <webElementGuid>2bd4a540-c52f-47a8-9ee4-b424ca6e248f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccione: Fecha de nacimiento del cliente dando click en el calendario</value>
      <webElementGuid>a86a7b8e-4571-4508-9b26-e2c4b0600a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFechaNacimientoPasaporte&quot;)</value>
      <webElementGuid>f12231bc-aac8-4052-9f78-ab8b69758df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      <webElementGuid>5e9a8c35-f59c-4628-b3d1-98f5782f6dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>98badef7-8c13-4049-b726-38c0ef9cf20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>1594b317-038e-4974-a27d-46287a0c644e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'F. Nacimiento' and @type = 'text' and @id = 'txtFechaNacimientoPasaporte' and @name = 'txtFechaNacimientoPasaporte' and @title = 'Seleccione: Fecha de nacimiento del cliente dando click en el calendario']</value>
      <webElementGuid>e5d927b2-3258-449a-8704-0bce47ded370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
