<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Es menor de edad_txtIdentificacion</name>
   <tag></tag>
   <elementGuidId>aefa22ce-59c8-498d-a115-f8fec47dcd71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ee84b7b-3275-480d-962f-8565f389c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>ef923929-7457-4bff-87f4-17f254f35f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Documento</value>
      <webElementGuid>e30a9644-3e40-45fd-85bf-8f7597c2d1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b27450c6-5ba0-4160-9ee8-e40231255d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtIdentificacion</value>
      <webElementGuid>69f048c0-2875-4afe-b055-a593f156b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtIdentificacion</value>
      <webElementGuid>211d708d-4add-4643-9d86-f9a449aab344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>8c56fad7-d405-472e-b4bc-ec7f8607c014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtIdentificacion&quot;)</value>
      <webElementGuid>e479dd0a-a5d3-4890-8019-dad512790a7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtIdentificacion']</value>
      <webElementGuid>89a7a66e-4fe6-4eb9-b5af-761740c76106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDatosCliente']/table/tbody/tr/td[3]/label/input</value>
      <webElementGuid>9ee4900b-1a3d-4951-85a5-c7cbbca6c165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/label/input</value>
      <webElementGuid>ed261e01-3390-4b05-92fb-98ca6fe5086b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Documento' and @type = 'text' and @id = 'txtIdentificacion' and @name = 'txtIdentificacion']</value>
      <webElementGuid>a0c8803b-5760-436d-9878-a67b3d417924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
