<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtDireccionPersonal_1</name>
   <tag></tag>
   <elementGuidId>5f9765ee-c4ee-43ab-87c2-9d3b3fc7353b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDireccionPersonal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDireccionPersonal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f28906d-621d-498e-b31a-35a4219e9460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>bd8748a3-1478-432f-91f3-991ea4ebe28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direccion</value>
      <webElementGuid>905d6600-abb7-4c99-a3c7-09b2c78c13da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb3e8a58-1dac-4224-936f-a665faef9999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>5a4ddb1c-80e3-43bf-a148-d1ffdcc56368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDireccionPersonal</value>
      <webElementGuid>4e925e30-7b3b-4c2f-8dbe-0c920757be12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f67581b7-575e-4a5c-9e5d-cfba0eb7b6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Dirección</value>
      <webElementGuid>54dd5bb4-7676-46a1-8d61-9ad715470c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDireccionPersonal&quot;)</value>
      <webElementGuid>e89a3bee-c8fd-4648-8ced-f6afb8afa388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDireccionPersonal']</value>
      <webElementGuid>33d72004-f02c-4eeb-aa14-5cddf0f9ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>e32e9979-7733-4c94-b12a-8e8b24214e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[5]/td/label/input[2]</value>
      <webElementGuid>9ac89a00-e428-4845-8669-5d0a28aacfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Direccion' and @type = 'text' and @id = 'txtDireccionPersonal' and @name = 'txtDireccionPersonal' and @title = 'Ingrese: Dirección']</value>
      <webElementGuid>ee56288b-ee28-46b5-990c-65278e1770b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
