<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Es menor de edad_txtIdentificacion_1</name>
   <tag></tag>
   <elementGuidId>4ba7b2f7-7673-4d23-a335-4fd81ade3ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtIdentificacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtIdentificacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b67fdf68-e410-4f39-a57f-bd600a0c13a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>3bc36583-db6e-4622-aa4e-b3a391da553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Documento</value>
      <webElementGuid>88d02ada-1e8c-42d1-8fc8-06bfdad52f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8012b101-e339-4335-86e1-00d1e966e1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtIdentificacion</value>
      <webElementGuid>b0178bd8-4244-423c-a59d-a0a2581666f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtIdentificacion</value>
      <webElementGuid>8a3876e9-40a9-4792-9b19-88e401837063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>0384174b-04e1-480f-affe-18cf63bcd502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Documento de identidad del cliente</value>
      <webElementGuid>fe66bd79-3c46-4eaa-bffa-555c697e3b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtIdentificacion&quot;)</value>
      <webElementGuid>b7337d54-dbab-4f08-9ecf-74d3de3d8347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtIdentificacion']</value>
      <webElementGuid>a5b90a05-7ae9-482d-a334-d5a980c0e5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDatosCliente']/table/tbody/tr/td[3]/label/input</value>
      <webElementGuid>dce8d567-6daa-4099-8841-9bf8ea2129e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/label/input</value>
      <webElementGuid>b44eff88-e0c0-44a9-b546-10f35c93805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Documento' and @type = 'text' and @id = 'txtIdentificacion' and @name = 'txtIdentificacion' and @title = 'Ingrese: Documento de identidad del cliente']</value>
      <webElementGuid>b02b3e06-1d4f-4615-bdb6-4c4db4bdf063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
