<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mujer_v_1</name>
   <tag></tag>
   <elementGuidId>aa43e64c-eaa0-4bb2-8862-827b608aadb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNumeroCargasPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNumeroCargasPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88cf9148-9bb0-4c70-afff-a8056ce889ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>2d32fc73-4aca-4687-adc8-c2b0451eb157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>N° Cargas</value>
      <webElementGuid>dc56a813-9f3f-4f31-85d8-654e296f4c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74fa69bc-7e87-4d01-8c89-e91826fba0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNumeroCargasPasaporte</value>
      <webElementGuid>f2377678-9ebf-42c6-95b0-5cd6a727656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>e130d516-a54d-49c7-8b40-da1fc3a91003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateNumbers(event)</value>
      <webElementGuid>58511e67-ea17-4729-8ef9-c18779e62c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese: Número de cargas del cliente</value>
      <webElementGuid>d7037607-47f1-48c8-a79a-9adf1fe5517e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNumeroCargasPasaporte&quot;)</value>
      <webElementGuid>25598eae-4ff9-4b8e-a535-0bebc65a0f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNumeroCargasPasaporte']</value>
      <webElementGuid>cfaef8db-80c4-4627-83ed-3c472714e6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[4]/td/input[2]</value>
      <webElementGuid>4736082d-260a-4934-93fa-d3c5d57ee462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input[2]</value>
      <webElementGuid>1531e228-7476-4a4a-baae-353810818086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'N° Cargas' and @type = 'text' and @id = 'txtNumeroCargasPasaporte' and @name = 'v' and @title = 'Ingrese: Número de cargas del cliente']</value>
      <webElementGuid>6065b7ab-7b6d-4b0a-9790-650fed1ea4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
