<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unin libre_txtFechaNacimientoPasaporte</name>
   <tag></tag>
   <elementGuidId>c33396a5-ecaf-4e6f-8cc8-3bb46a4f1297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFechaNacimientoPasaporte</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3b77829-0484-4c44-aaca-488483918916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip hasDatepicker</value>
      <webElementGuid>976ea3a6-2bf7-409c-9dff-4dc2e4cf6147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>F. Nacimiento</value>
      <webElementGuid>626878f9-adca-4b73-a112-9491ad61754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4aacc3cb-ed27-4878-ad25-2ac5a59c5eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>4c0469f8-405b-46bf-80fd-786207d279e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtFechaNacimientoPasaporte</value>
      <webElementGuid>06c8bb22-31b3-449a-9182-269a2c49e957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return controlIngresoFecha(event)</value>
      <webElementGuid>4def959b-b19e-4485-ac5d-961e8e083e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidarFechaNacimiento(this)</value>
      <webElementGuid>e4384693-3bda-4fc1-8008-3ad3bf3188e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFechaNacimientoPasaporte&quot;)</value>
      <webElementGuid>a9d80c3a-b7f8-4579-9fed-fcf995e29c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFechaNacimientoPasaporte']</value>
      <webElementGuid>e3b20e17-5a3b-48f8-85ea-31b9793dca72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trBloquePasaporte']/td/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>e3a8f155-d28b-4680-a9c4-e04821f527e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>8a0c2163-127b-4a63-9d5a-b4e31a039b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'F. Nacimiento' and @type = 'text' and @id = 'txtFechaNacimientoPasaporte' and @name = 'txtFechaNacimientoPasaporte']</value>
      <webElementGuid>c4c08bbf-f0a7-44ae-bcf6-bf7d4d3457c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
