<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REFERENCIAS PERSONALES_txtParentesco</name>
   <tag></tag>
   <elementGuidId>275cf84f-e5a4-4b94-bd35-70e30a9980d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtParentesco</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtParentesco']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d31b9af2-4c79-4af1-85d6-9b23dcfa6970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>masterTooltip</value>
      <webElementGuid>7e1a6249-c7ce-4f04-b105-67911415fa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Parentesco</value>
      <webElementGuid>ed820eb6-8b8c-4847-912b-ef29431da5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b682563-6da6-442e-98dc-cdecca234a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtParentesco</value>
      <webElementGuid>52064c2b-db30-4a87-8aa3-d0e7546993a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtParentesco</value>
      <webElementGuid>62e5dd8d-7229-4f48-acbf-640899555da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c15784d0-9e1b-48f5-b786-58c7b764f264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateChars(event)</value>
      <webElementGuid>03f6ac54-2f87-41ce-a114-c09029fcfba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtParentesco&quot;)</value>
      <webElementGuid>6430363b-b5cb-49b8-93dc-0dccf30d9acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtParentesco']</value>
      <webElementGuid>1b61eec1-8f39-439e-a3a2-a64f7f4f1ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divReferencias']/table/tbody/tr[5]/td/label/input[4]</value>
      <webElementGuid>20678afa-560a-46a6-b910-67b4816926da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/label/input[4]</value>
      <webElementGuid>071dc19e-6d7c-4538-923c-dc0635c38222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Parentesco' and @type = 'text' and @id = 'txtParentesco' and @name = 'txtParentesco']</value>
      <webElementGuid>3904bb70-d2d4-46fe-8306-5f39a333a872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
