<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>6a030482-ec66-4d04-8ad2-d0d2aa846112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#divSituacionEconomica > table.NoBorders > tbody > tr > td > label > label.squaredFour > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divSituacionEconomica']/table/tbody/tr/td/label/label[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2b316b3a-1c6f-4bab-9532-c3d09208b519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chkPrimerTrabajo</value>
      <webElementGuid>bcf03ec7-89b2-46d2-b523-c210aff587bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divSituacionEconomica&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[1]/td[1]/label[1]/label[@class=&quot;squaredFour&quot;]/label[1]</value>
      <webElementGuid>5285e25d-d64d-4541-93fc-7f061830ca20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divSituacionEconomica']/table/tbody/tr/td/label/label[2]/label</value>
      <webElementGuid>47640785-ff67-4bc7-9ade-30bab378a795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr/td/label/label[2]/label</value>
      <webElementGuid>d5d6288e-20fe-4159-af92-e6808d2740ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
