<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NO</name>
   <tag></tag>
   <elementGuidId>91e8314d-fdae-4e78-bff7-c1f1cdabb852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>88195d45-e7fb-4f6b-95d6-8f0ca797fe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>rbResideNO</value>
      <webElementGuid>c3cd7799-7ddd-403d-8476-15fe0ac29511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-label cb0 radGroup1</value>
      <webElementGuid>f0d747a5-234f-4db7-988d-aab489b64689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>fa0b8da4-e221-417f-9d2c-9f7d747200bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divDireccion&quot;)/table[@class=&quot;NoBorders&quot;]/tbody[1]/tr[8]/td[1]/label[@class=&quot;css-label cb0 radGroup1&quot;]</value>
      <webElementGuid>609cebbc-a2fa-4a16-b3df-c8984706dac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDireccion']/table/tbody/tr[8]/td/label[3]</value>
      <webElementGuid>ee55fea7-1303-4d63-b4af-3787709887fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[1]/following::label[1]</value>
      <webElementGuid>65ff095b-13e1-4c43-bc61-cf3823a894de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Es residente fiscal en Ecuador?:'])[1]/following::label[2]</value>
      <webElementGuid>81a30c8b-2ab8-47d6-8f4d-dea5ae43af77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tributa en el exterior?:'])[1]/preceding::label[1]</value>
      <webElementGuid>f4c21296-e1f4-41a5-bc5f-c9d772c2e857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Obligación Tributaria:'])[1]/preceding::label[5]</value>
      <webElementGuid>de789f16-8cc3-485a-b3f0-68a15f319d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO']/parent::*</value>
      <webElementGuid>5e1189ed-cab8-4359-9127-3d04c02ae5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label[3]</value>
      <webElementGuid>9452ae9a-cdc2-4d03-8dcc-e6e4332fc482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'NO' or . = 'NO')]</value>
      <webElementGuid>6d48d6c6-a46a-4a98-9f3d-566576e513a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
