<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUDITOR</name>
   <tag></tag>
   <elementGuidId>2940f027-39c2-4cb5-9f48-25c8dd66421e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbOcupacion_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbOcupacion_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>47bf52ae-8cea-44bc-b1d5-360c34ad8e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>2bb59aa5-6ba2-4c3a-bf64-1606ccd536b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>67</value>
      <webElementGuid>b5f4b980-7901-49fb-9bd4-4f70fbc6d9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUDITOR                                           </value>
      <webElementGuid>6f581ce1-5a42-42e3-b309-34cff5e8b3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbOcupacion_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>b65adf84-d411-4f81-8043-724a84e900af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbOcupacion_chosen']/div/ul/li</value>
      <webElementGuid>43f4f207-6cdb-4f09-b43b-aed383a539a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUDITOR'])[2]/following::li[1]</value>
      <webElementGuid>6f70f0f9-83d7-4586-bc55-9885090a406a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocupación:'])[1]/following::li[1]</value>
      <webElementGuid>9be97ca9-e9ab-43cc-8085-d739ba877c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DITOR']/parent::*</value>
      <webElementGuid>3e43a53c-9d12-4ec1-a3c9-7e24bdae2c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/label/div/div/ul/li</value>
      <webElementGuid>5ac3bb24-30b4-4de7-bc4f-5d7febf2db9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'AUDITOR                                           ' or . = 'AUDITOR                                           ')]</value>
      <webElementGuid>cc93c573-bab6-4352-8e0f-7ee447356c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
