<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AHORROS</name>
   <tag></tag>
   <elementGuidId>cbcfffe2-26cf-4e12-8b1a-26e666657be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbPropositoRelacion_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbPropositoRelacion_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ed56fd0e-3681-4ce9-8e9e-fdc9eaeec35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>ba9508c0-fbc4-4e7f-9dec-3284bae2ef27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad950015-4195-42b1-af13-9e285f133e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AHORROS</value>
      <webElementGuid>750e85b6-607b-47da-ae43-f52ff5577b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbPropositoRelacion_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>e6cb3ae8-a8db-485f-a835-5bc77f989460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbPropositoRelacion_chosen']/div/ul/li</value>
      <webElementGuid>8405e9aa-bcad-4649-bf28-9812144906c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AHORROS'])[4]/following::li[1]</value>
      <webElementGuid>51a9930c-770f-496c-92b6-e6b79d27a378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propósito relación:'])[1]/following::li[1]</value>
      <webElementGuid>48ae0308-bdf6-4f3f-8eec-41b3a791b7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CDP'])[2]/preceding::li[1]</value>
      <webElementGuid>396686b4-2bb5-4cb9-8d28-1f3d0cb5b46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOCACIONES'])[2]/preceding::li[2]</value>
      <webElementGuid>10b0630a-4146-4def-9845-bdeb5df01295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/table/tbody/tr/td/label/div/div/ul/li</value>
      <webElementGuid>63927945-71ce-43ee-8aa5-cf7e213f1a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'AHORROS' or . = 'AHORROS')]</value>
      <webElementGuid>c90ca099-5677-4db9-9a36-21ee082a8651</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
