<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Ecuador</name>
   <tag></tag>
   <elementGuidId>43d5a19d-3874-43b8-a1fc-3bcc4c70eac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbNacionalidad1_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbNacionalidad1_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>60978ed3-49ff-4412-90b2-105c930e1395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>fe698cd7-6fb5-4c7d-9cc6-b91ee7f9c68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>59935721-d275-4bc8-bf64-8c3737d65b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ecuador</value>
      <webElementGuid>a8fc53f9-ebe2-4c26-8feb-b86d45ef1dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbNacionalidad1_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>88bea775-7837-4560-8ea1-00b14dff1f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbNacionalidad1_chosen']/div/ul/li</value>
      <webElementGuid>e478e9cc-04cb-4f95-99de-fcfa4b311b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ecuador'])[2]/following::li[1]</value>
      <webElementGuid>9d244f0c-9013-4c77-826f-407d4b80f82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nacionalidad 1:'])[1]/following::li[1]</value>
      <webElementGuid>e8ab7062-d7a1-4e4d-a4fc-80fe60316188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='uador']/parent::*</value>
      <webElementGuid>82af7aaf-4f0c-440d-9b75-9ddffc69ee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/div/label/div/div/ul/li</value>
      <webElementGuid>9ac1fdd2-862c-449e-bc82-4784d8cb9e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Ecuador' or . = 'Ecuador')]</value>
      <webElementGuid>86ba078f-db13-49b4-b322-b2e1fb6b32f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
