<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mestizoa</name>
   <tag></tag>
   <elementGuidId>d4d1f2d8-1a00-48ef-8cf0-c29183e31c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbGrupoEtnico_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbGrupoEtnico_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2dc24e42-dbfa-4fb8-ae57-beeb0211f3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>7b5a998f-e766-447b-8859-f84df6431f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d580920a-8683-4d14-93ba-d76b3f77c2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mestizo/a</value>
      <webElementGuid>d747c53b-3360-4160-9dfb-e59757c4f38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbGrupoEtnico_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>ae8e437e-6d7a-40cf-8344-5a09f6005094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbGrupoEtnico_chosen']/div/ul/li</value>
      <webElementGuid>d557d1a7-0078-41ca-9b8d-eb4c6efe8ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mestizo/a'])[2]/following::li[1]</value>
      <webElementGuid>8da1c30d-e7a5-41f9-96bf-6eb694f6863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo Étnico:'])[1]/following::li[1]</value>
      <webElementGuid>6883886f-3764-4c62-adba-79eaf118ce09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montuvio/a'])[2]/preceding::li[1]</value>
      <webElementGuid>7bffa158-fd22-4af4-af6f-48e5fbfd3e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De una nacionalidad o pueblo indígena'])[2]/preceding::li[2]</value>
      <webElementGuid>55a9a973-323b-4543-871b-99b625c16f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/div/div/ul/li</value>
      <webElementGuid>4d7d417a-f4f4-41e5-88d8-3b5a48d1d0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Mestizo/a' or . = 'Mestizo/a')]</value>
      <webElementGuid>73785cf5-dbe5-405d-ac63-d6f74d3bcf0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
