<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Soltero(a)</name>
   <tag></tag>
   <elementGuidId>8afb40f7-d53f-4b1c-b472-88c780b5b59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbEstadoCivilPasaporte_chosen > div.chosen-drop > ul.chosen-results > li.active-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cbEstadoCivilPasaporte_chosen']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fd9e9b8f-84d9-4aca-88c9-634287e90246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>1d802822-9a87-4126-a5b3-b27a56a8fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>72cb6353-0571-4c08-beb9-f06498fdb8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Soltero(a)</value>
      <webElementGuid>6e01b0b6-7841-4bfa-a19a-b2e320063af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbEstadoCivilPasaporte_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>1113fb09-3f12-45af-828a-32a621fb95ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cbEstadoCivilPasaporte_chosen']/div/ul/li</value>
      <webElementGuid>1a12d138-4a19-4767-8178-eebb0646436d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soltero(a)'])[4]/following::li[1]</value>
      <webElementGuid>f8f098d8-9c4b-4f3f-9ca5-4f1c161446ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil:'])[3]/following::li[1]</value>
      <webElementGuid>f9f64400-6995-4e41-a718-f9718c88c4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casado(a)'])[3]/preceding::li[1]</value>
      <webElementGuid>aa1a8b80-9fe0-4e87-acc6-4665632baf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viudo(a)'])[3]/preceding::li[2]</value>
      <webElementGuid>eed31d6f-2e71-4165-91d6-f3c688e42381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label/div/div/ul/li</value>
      <webElementGuid>deed3ec3-da5d-4736-9768-d760e1920a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Soltero(a)' or . = 'Soltero(a)')]</value>
      <webElementGuid>0e60bc31-03d2-4100-873f-7d0f58a83355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
